### ISSUE TITLE
Fails to build with Qt6 (-DENABLE_QT6=ON)

### ISSUE THREAD

**Issue by jbeich** [yuzu-emu/yuzu#9680]
Regressed by #9668 due to qt/qtbase@c9b2528a9d60. From [error log](https://github.com/yuzu-emu/yuzu/files/10504625/yuzu-qt6-s20230125.log):
```c++
src/yuzu/main.cpp:4458:40: error: no member named 'AA_DisableWindowContextHelpButton' in namespace 'Qt'
    QCoreApplication::setAttribute(Qt::AA_DisableWindowContextHelpButton);
                                   ~~~~^
```
