### ISSUE TITLE
Fails to build with Qt6

### ISSUE THREAD

**Issue by jbeich** [yuzu-emu/yuzu#9464]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

5da72a891fb4 (`master` snapshot)

### Description of Issue

Regressed by #9451. From [error log](https://github.com/yuzu-emu/yuzu/files/10252957/yuzu-qt6-s20221217.log):
```c++
src/yuzu/bootmanager.cpp:825:20: error: use of undeclared identifier 'CAMERA_WIDTH'
        img.scaled(CAMERA_WIDTH, CAMERA_HEIGHT, Qt::AspectRatioMode::IgnoreAspectRatio,
                   ^
src/yuzu/bootmanager.cpp:825:34: error: use of undeclared identifier 'CAMERA_HEIGHT'
        img.scaled(CAMERA_WIDTH, CAMERA_HEIGHT, Qt::AspectRatioMode::IgnoreAspectRatio,
                                 ^
src/yuzu/bootmanager.cpp:828:17: error: use of undeclared identifier 'camera_data'
    std::memcpy(camera_data.data(), converted.bits(), CAMERA_WIDTH * CAMERA_HEIGHT * sizeof(u32));
                ^
src/yuzu/bootmanager.cpp:828:55: error: use of undeclared identifier 'CAMERA_WIDTH'
    std::memcpy(camera_data.data(), converted.bits(), CAMERA_WIDTH * CAMERA_HEIGHT * sizeof(u32));
                                                      ^
src/yuzu/bootmanager.cpp:828:70: error: use of undeclared identifier 'CAMERA_HEIGHT'
    std::memcpy(camera_data.data(), converted.bits(), CAMERA_WIDTH * CAMERA_HEIGHT * sizeof(u32));
                                                                     ^
src/yuzu/bootmanager.cpp:829:49: error: use of undeclared identifier 'CAMERA_WIDTH'
    input_subsystem->GetCamera()->SetCameraData(CAMERA_WIDTH, CAMERA_HEIGHT, camera_data);
                                                ^
src/yuzu/bootmanager.cpp:829:63: error: use of undeclared identifier 'CAMERA_HEIGHT'
    input_subsystem->GetCamera()->SetCameraData(CAMERA_WIDTH, CAMERA_HEIGHT, camera_data);
                                                              ^
src/yuzu/bootmanager.cpp:829:78: error: use of undeclared identifier 'camera_data'
    input_subsystem->GetCamera()->SetCameraData(CAMERA_WIDTH, CAMERA_HEIGHT, camera_data);
                                                                             ^
```

### Expected Behavior

Builds fine

### Reproduction Steps

```
$ cmake -DENABLE_QT6=ON -G Ninja -B /tmp/yuzu_build
$ cmake --build /tmp/yuzu_build
```

### Log File

Not available (doesn't build)

### System Configuration

Linux-like
