### ISSUE TITLE
mingw 9.3.0: lambda parameter ‘perm’ previously declared as a capture

### ISSUE THREAD

**Issue by gxcreator** [yuzu-emu/yuzu#3773]
Build with mingw 9.3.0 + mainline + early-access patches:

```
../src/core/hle/kernel/memory/page_table.cpp: In lambda function:
../src/core/hle/kernel/memory/page_table.cpp:857:91: error: lambda parameter ‘perm’ previously declared as a capture
  857 |                               [perm](MemoryBlockManager::iterator block, MemoryPermission perm) {
      |                                                                          ~~~~~~~~~~~~~~~~~^~~~
../src/core/hle/kernel/memory/page_table.cpp: In lambda function:
../src/core/hle/kernel/memory/page_table.cpp:879:91: error: lambda parameter ‘perm’ previously declared as a capture
  879 |                               [perm](MemoryBlockManager::iterator block, MemoryPermission perm) {
      |   
```

It seems it is not needed to declare capture, since perm will be passed to callback. Or is it some hack made intentionally?

**Comment by H27CK** [comment]
I've been solving this by removing `perm` as a capture, as you suggest. All seems to operate as expected, but I don't fully appreciate the implications (if any).

**Comment by lat9nq** [comment]
This is related to just now merging PR #3707 @bunnei. I get the same error on my Manjaro machine.

**Comment by gxcreator** [comment]
For me, it builds and works ok after removing `perm` from capture. I believe it is here by mistake, but need a confirmation from someone who has knowledge what this code actually does.
