### PR TITLE
cmake: pass libusb include directory

### LINKED ISSUE #4279: Build fails on linux due to libusb
The current version (77bdd09) fails to build on linux due to libusb.h missing
I'm on arch linux, kernel 5.7.4-8-tkg-pds and gcc 10.1.0-2 (I think the new building system still uses gcc, right?)

Anyways, here's the relevant output from the compiler:

`FAILED: src/input_common/CMakeFiles/input_common.dir/gcadapter/gc_adapter.cpp.o 
/usr/bin/c++  -DARCHITECTURE_x86_64=1 -DBOOST_ALL_NO_LIB -DBOOST_CONTEXT_DYN_LINK -DBOOST_DATE_TIME_NO_LIB -DBOOST_ERROR_CODE_HEADER_ONLY -DBOOST_REGEX_NO_LIB -DBOOST_SYSTEM_NO_LIB -DFMT_LOCALE -DFMT_SHARED -DHAVE_SDL2 -DNDEBUG -D_FILE_OFFSET_BITS=64 -I../src/. -I../externals/./microprofile -isystem /usr/include/SDL2 -O3 -DNDEBUG   -Wall -Werror=implicit-fallthrough -Werror=missing-declarations -Werror=reorder -Wextra -Wmissing-declarations -Wno-attributes -Wno-unused-parameter -mcx16 -std=gnu++17 -MD -MT src/input_common/CMakeFiles/input_common.dir/gcadapter/gc_adapter.cpp.o -MF src/input_common/CMakeFiles/input_common.dir/gcadapter/gc_adapter.cpp.o.d -o src/input_common/CMakeFiles/input_common.dir/gcadapter/gc_adapter.cpp.o -c ../src/input_common/gcadapter/gc_adapter.cpp
In file included from ../src/input_common/gcadapter/gc_adapter.cpp:8:
../src/./input_common/gcadapter/gc_adapter.h:11:10: fatal error: libusb.h: No such file or directory
   11 | #include <libusb.h>
      |          ^~~~~~~~~~
compilation terminated.`
This appears to be related to the recent gamecube controller support.
I don't know if any more information is required, so feel free to ask for any additional info

### PR DESCRIPTION
**Pull request by jbeich**
Regressed by #4266 
Fixes #4279

Reference libusb (unlike FreeBSD implementation) has `libusb-1.0/` directory prefix, so include directory from `pkg-config --cflags libusb-1.0` needs to be passed properly.

### CODE REVIEW

**Comment by RealJohnGalt** [comment]
I can confirm this fixes the build on Arch with system libusb, so LGTM. Thank you!

**Comment by RealJohnGalt** [comment]
In case your new change also fails on the linux buildbot, this change should work on both: http://ix.io/2rh7

File: src/input_common/CMakeLists.txt [hunk 1]
```diff
@@ -30,6 +30,7 @@ if(SDL2_FOUND)
     target_compile_definitions(input_common PRIVATE HAVE_SDL2)
 endif()
 
+target_include_directories(input_common SYSTEM PUBLIC ${LIBUSB_INCLUDE_DIR})
```
Comment (lioncash) [inline src/input_common/CMakeLists.txt:33]: This is likely able to be made private, if a forward declaration is added to the GC adapter header, and the libusb header is moved into the cpp file.

**Comment by ogniK5377** [comment]
Build is successful locally on my windows machine.

**Comment by lioncash** [comment]
Hi, when you have time can you address the review comments so that this can be merged?

File: src/input_common/CMakeLists.txt (hunk 1 above)
Comment (jbeich) [reply src/input_common/CMakeLists.txt]: `PUBLIC` here was for consistency with `target_link_libraries`. However, with static libraries (like `input_common`) the boundary between public and private dependency is blurry.

Sorry, I was under impression your comment was an idea for a separate PR.

**Comment by ameerj** [comment]
Sorry for not mentioning this earlier. You can also remove the libusb.h include in input_common/main.cpp. That was a remnant of an early implementation.
