### ISSUE TITLE
Has the required Compiler version changed.

### ISSUE THREAD

**Issue by mickski56** [yuzu-emu/yuzu#13131]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

812f23d05c77fb10407546c3e7a95447fcbea395

### Description of Issue

Build failure with 
error: no type named 'mapped_type'

gcc or clang makes no difference.
812f23d05c77fb10407546c3e7a95447fcbea395 is first bad commit.

### Expected Behavior

Build success

### Reproduction Steps

Try to build on slackware64 15.0 

### Log File

bits/unordered_map.h:113:36: error: no type named 'mapped_type' in 'std::_Hashtable<unsigned long, std::pair<const unsigned long, Service::VI::VsyncManager>, std::allocator<std::pair<const unsigned long, Service::VI::VsyncManager>>, std::__detail::_Select1st, std::equal_to<unsigned long>, std::hash<unsigned long>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true>>'

full build log can be supplied if required.

### System Configuration

CPU: amd 5500
GPU/Driver: 1080ti
RAM:32GB
OS: slackware64 15.0

**Comment by liamwhite** [comment]
what compiler version and libstdc++ version is this?

**Comment by mickski56** [comment]
gcc (GCC) 11.2.0

libstdc++.so.6.0.29 is part of the gcc-g++-11.2.0 package on slackware64 15

**Comment by liamwhite** [comment]
For reference, this appears to be a regression in a specific version of libstdc++ that was already fixed: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=104174

It can likely be worked around [here](https://github.com/yuzu-emu/yuzu/blob/master/src/core/hle/service/vi/conductor.cpp#L19) like this:
`u64 id = display.GetId(); m_vsync_managers.insert({id, VsyncManager{}});`

Closing as this is a library bug but let me know if this fixes it

**Comment by mickski56** [comment]
I'm so sorry I posted the wrong error messages. The first error is 

stl_pair.h:218:11: error: field has incomplete type 'Service::VI::VsyncManager'
      _T2 second;                ///< The second member

**Comment by liamwhite** [comment]
Ok and what .cpp file generates this? Is it conductor.cpp?

**Comment by mickski56** [comment]
First 70% snipped 
make >build.log 2>&1

[build.log](https://github.com/yuzu-emu/yuzu/files/14386597/build.log)

Can redo with VERBOSE=1 if required.

**Comment by liamwhite** [comment]
add `#include "core/hle/service/vi/vsync_manager.h"` to core/hle/service/vi/conductor.h and see if that fixes it. this is still a standard library bug as it should not be trying to instantiate the member from an external path.

**Comment by mickski56** [comment]
Yes that did the trick
Thanks.
