### ISSUE TITLE
Fails to build with Clang

### ISSUE THREAD

**Issue by jbeich** [yuzu-emu/yuzu#3407]
Regressed by https://github.com/yuzu-emu/yuzu/pull/3337, see [error log](https://github.com/yuzu-emu/yuzu/files/4195470/yuzu-qt5-s20200212.log). GCC is not affected. CC @ReinUsesLisp

```c++
$ CC=clang CXX=clang++ cmake -GNinja /path/to/yuzu
$ ninja
[...]
src/video_core/renderer_vulkan/renderer_vulkan.cpp:40:61: error:
      non-constant-expression cannot be narrowed from type
      'VkDebugUtilsMessageSeverityFlagBitsEXT' to
      'vk::DebugUtilsMessageSeverityFlagBitsEXT' in initializer list
      [-Wc++11-narrowing]
    const vk::DebugUtilsMessageSeverityFlagBitsEXT severity{severity_};
                                                            ^~~~~~~~~
```

**Comment by ReinUsesLisp** [comment]
Try changing it to:
```cpp
const vk::DebugUtilsMessageSeverityFlagBitsEXT severity = severity_;
```

**Comment by jbeich** [comment]
@ReinUsesLisp, doesn't help:
```c++
src/video_core/renderer_vulkan/renderer_vulkan.cpp:40:52: error: cannot
      initialize a variable of type 'const vk::DebugUtilsMessageSeverityFlagBitsEXT'
      with an lvalue of type 'VkDebugUtilsMessageSeverityFlagBitsEXT'
    const vk::DebugUtilsMessageSeverityFlagBitsEXT severity = severity_;
                                                   ^          ~~~~~~~~~
```

**Comment by jroweboy** [comment]
@jbeich Hey I just ran into this problem too, and I've temporarily resolved this with 
```
    const vk::DebugUtilsMessageSeverityFlagBitsEXT severity = static_cast<vk::DebugUtilsMessageSeverityFlagBitsEXT>(severity_);
```

**Comment by jbeich** [comment]
Fixed by bf1d66b7c074c02aa8148f2edbdc959082c229e1.
