### ISSUE TITLE
Fails to build with Clang

### ISSUE THREAD

**Issue by jbeich** [yuzu-emu/yuzu#2863]
Regressed by #2759 (1f43e5296fcd). Affects Clang 5/6/7/8/9 but not GCC 7/8/9. [Full build log](https://github.com/yuzu-emu/yuzu/files/3615919/yuzu-qt5-s20190915.log).

```c++
$ git describe --tags --always
393cc3ef2

$ c++ --version
FreeBSD clang version 8.0.1 (tags/RELEASE_801/final 366581) (based on LLVM 8.0.1)
Target: x86_64-unknown-freebsd13.0
Thread model: posix
InstalledDir: /usr/bin

$ cmake -GNinja /path/to/yuzu
$ ninja
[...]
FAILED: src/video_core/CMakeFiles/video_core.dir/renderer_opengl/gl_shader_decompiler.cpp.o
/usr/bin/c++  -DARCHITECTURE_x86_64=1 -DHAS_VULKAN -DNDEBUG -I/path/to/yuzu/src/. -I/path/to/yuzu/src/video_core/sirit -I/path/to/yuzu/src/video_core/../../externals/Vulkan-Headers/include -I/path/to/yuzu/externals/fmt/include -I/path/to/yuzu/externals/./microprofile -I/path/to/yuzu/externals/glad/include -I/path/to/yuzu/externals/sirit/src/../include -I/path/to/yuzu/externals/sirit/externals/SPIRV-Headers/include -isystem /usr/local/include -O3 -DNDEBUG   -Wall -Wno-attributes -std=gnu++17 -MD -MT src/video_core/CMakeFiles/video_core.dir/renderer_opengl/gl_shader_decompiler.cpp.o -MF src/video_core/CMakeFiles/video_core.dir/renderer_opengl/gl_shader_decompiler.cpp.o.d -o src/video_core/CMakeFiles/video_core.dir/renderer_opengl/gl_shader_decompiler.cpp.o -c /path/to/yuzu/src/video_core/renderer_opengl/gl_shader_decompiler.cpp
/path/to/yuzu/src/video_core/renderer_opengl/gl_shader_decompiler.cpp:710:25: error: reference to local binding 'image' declared in enclosing function 'OpenGL::GLShader::(anonymous namespace)::GLSLDecompiler::DeclareImages'
                switch (image.GetType()) {
                        ^
/path/to/yuzu/src/video_core/renderer_opengl/gl_shader_decompiler.cpp:708:35: note: 'image' declared here
        for (const auto& [offset, image] : images) {
                                  ^
/path/to/yuzu/src/video_core/renderer_opengl/gl_shader_decompiler.cpp:730:22: error: reference to local binding 'image' declared in enclosing function 'OpenGL::GLShader::(anonymous namespace)::GLSLDecompiler::DeclareImages'
                if (!image.IsSizeKnown()) {
                     ^
/path/to/yuzu/src/video_core/renderer_opengl/gl_shader_decompiler.cpp:708:35: note: 'image' declared here
        for (const auto& [offset, image] : images) {
                                  ^
/path/to/yuzu/src/video_core/renderer_opengl/gl_shader_decompiler.cpp:733:25: error: reference to local binding 'image' declared in enclosing function 'OpenGL::GLShader::(anonymous namespace)::GLSLDecompiler::DeclareImages'
                switch (image.GetSize()) {
                        ^
/path/to/yuzu/src/video_core/renderer_opengl/gl_shader_decompiler.cpp:708:35: note: 'image' declared here
        for (const auto& [offset, image] : images) {
                                  ^
/path/to/yuzu/src/video_core/renderer_opengl/gl_shader_decompiler.cpp:740:56: error: reference to local binding 'image' declared in enclosing function 'OpenGL::GLShader::(anonymous namespace)::GLSLDecompiler::DeclareImages'
                                      static_cast<u32>(image.GetSize()));
                                                       ^
/path/to/yuzu/src/video_core/renderer_opengl/gl_shader_decompiler.cpp:708:35: note: 'image' declared here
        for (const auto& [offset, image] : images) {
                                  ^
/path/to/yuzu/src/video_core/renderer_opengl/gl_shader_decompiler.cpp:1246:30: warning: unused variable 'constructors' [-Wunused-variable]
        constexpr std::array constructors{"int(", "ivec2(", "ivec3(", "ivec4("};
                             ^
1 warning and 4 errors generated.
```
