### ISSUE TITLE
Compiling yuzu-mainline fails on latest builds [Linux]

### ISSUE THREAD

**Issue by Shoegzer** [yuzu-emu/yuzu#3790]
Compiling yuzu-mainline under linux-gcc fails with commit 8f548266cd0493a537ed7edf56c869bd7420953a.  Last successful compile was several days before, on commit d551c910bbd0570e953b3c769e08ae7edc495e3c.  Can perform a bisect if needed.

**Update**: Performed a bisect.  First bad commit is b52097804334307103cfaba72cd6e27db804f650

Test system is Linux Mint 19.3 (ubuntu 18.04 based), kernel 5.3 with gcc 9.3.0.

Compile log excerpt:
```
/home/shoegzer/Desktop/yuzu/yuzu-mainline/src/common/lz4_compression.cpp:14:31: error: ‘LZ4_MAX_INPUT_SIZE’ was not declared in this scope
   14 |     ASSERT_MSG(source_size <= LZ4_MAX_INPUT_SIZE, "Source size exceeds LZ4 maximum input size");
      |                               ^~~~~~~~~~~~~~~~~~
/home/shoegzer/Desktop/yuzu/yuzu-mainline/src/./common/assert.h:36:11: note: in definition of macro ‘ASSERT_MSG’
   36 |     if (!(_a_)) {                                                                                  \
      |           ^~~
...
[ 54%] Linking CXX static library libdynarmic.a
[ 54%] Built target dynarmic
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
```
Full log is here: [yuzu_compile.log](https://github.com/yuzu-emu/yuzu/files/4541287/yuzu_compile.log)

**Comment by joker5bb** [comment]
I also have fail of compile 
`[ 55%] Building CXX object src/video_core/CMakeFiles/video_core.dir/textures/astc.cpp.o
/home/user/yuzu-mainline/src/video_core/textures/astc.cpp:196:23: error: ‘static_vector_options’ is not a member of ‘boost::container’; did you mean ‘vector_options’?
  196 |     boost::container::static_vector_options<
      |                       ^~~~~~~~~~~~~~~~~~~~~
      |                       vector_options
/home/user/yuzu-mainline/src/video_core/textures/astc.cpp:197:27: error: ‘inplace_alignment’ is not a member of ‘boost::container’
  197 |         boost::container::inplace_alignment<alignof(IntegerEncodedValue)>,
      |                           ^~~~~~~~~~~~~~~~~
/home/user/yuzu-mainline/src/video_core/textures/astc.cpp:197:73: error: wrong number of template arguments (3, should be 2)
  197 |         boost::container::inplace_alignment<alignof(IntegerEncodedValue)>,
      |                                                                         ^
In file included from /usr/include/boost/container/vector.hpp:26,
                 from /usr/include/boost/container/static_vector.hpp:25,
                 from /home/user/yuzu-mainline/src/video_core/textures/astc.cpp:23:
/usr/include/boost/container/container_fwd.hpp:106:7: note: provided for ‘template<class T, long unsigned int Capacity> class boost::container::static_vector’
  106 | class static_vector;
      |       ^~~~~~~~~~~~~
/home/user/yuzu-mainline/src/video_core/textures/astc.cpp:200:51: error: ‘IntegerEncodedVector’ has not been declared
  200 | static void DecodeTritBlock(InputBitStream& bits, IntegerEncodedVector& result, u32 nBitsPerValue) {
      |                                                   ^~~~~~~~~~~~~~~~~~~~
/home/user/yuzu-mainline/src/video_core/textures/astc.cpp: In function ‘void DecodeTritBlock(InputBitStream&, int&, u32)’:
/home/user/yuzu-mainline/src/video_core/textures/astc.cpp:252:43: error: request for member ‘emplace_back’ in ‘result’, which is of non-class type ‘int’
  252 |         IntegerEncodedValue& val = result.emplace_back(IntegerEncoding::Trit, nBitsPerValue);
      |                                           ^~~~~~~~~~~~
/home/user/yuzu-mainline/src/video_core/textures/astc.cpp: At global scope:
/home/user/yuzu-mainline/src/video_core/textures/astc.cpp:258:52: error: ‘IntegerEncodedVector’ has not been declared
  258 | static void DecodeQus32Block(InputBitStream& bits, IntegerEncodedVector& result,
      |                                                    ^~~~~~~~~~~~~~~~~~~~
/home/user/yuzu-mainline/src/video_core/textures/astc.cpp: In function ‘void DecodeQus32Block(InputBitStream&, int&, u32)’:
/home/user/yuzu-mainline/src/video_core/textures/astc.cpp:299:43: error: request for member ‘emplace_back’ in ‘result’, which is of non-class type ‘int’
  299 |         IntegerEncodedValue& val = result.emplace_back(IntegerEncoding::Qus32, nBitsPerValue);
      |                                           ^~~~~~~~~~~~
/home/user/yuzu-mainline/src/video_core/textures/astc.cpp: At global scope:
/home/user/yuzu-mainline/src/video_core/textures/astc.cpp:346:35: error: variable or field ‘DecodeIntegerSequence’ declared void
  346 | static void DecodeIntegerSequence(IntegerEncodedVector& result, InputBitStream& bits, u32 maxRange,
      |                                   ^~~~~~~~~~~~~~~~~~~~
/home/user/yuzu-mainline/src/video_core/textures/astc.cpp:346:35: error: ‘IntegerEncodedVector’ was not declared in this scope; did you mean ‘IntegerEncodedValue’?
  346 | static void DecodeIntegerSequence(IntegerEncodedVector& result, InputBitStream& bits, u32 maxRange,
      |                                   ^~~~~~~~~~~~~~~~~~~~
      |                                   IntegerEncodedValue
/home/user/yuzu-mainline/src/video_core/textures/astc.cpp:346:57: error: ‘result’ was not declared in this scope
  346 | static void DecodeIntegerSequence(IntegerEncodedVector& result, InputBitStream& bits, u32 maxRange,
      |                                                         ^~~~~~
/home/user/yuzu-mainline/src/video_core/textures/astc.cpp:346:79: error: expected primary-expression before ‘&’ token
  346 | static void DecodeIntegerSequence(IntegerEncodedVector& result, InputBitStream& bits, u32 maxRange,
      |                                                                               ^
/home/user/yuzu-mainline/src/video_core/textures/astc.cpp:346:81: error: ‘bits’ was not declared in this scope; did you mean ‘Bits’?
  346 | static void DecodeIntegerSequence(IntegerEncodedVector& result, InputBitStream& bits, u32 maxRange,
      |                                                                                 ^~~~
      |                                                                                 Bits
/home/user/yuzu-mainline/src/video_core/textures/astc.cpp:346:91: error: expected primary-expression before ‘maxRange’
  346 | static void DecodeIntegerSequence(IntegerEncodedVector& result, InputBitStream& bits, u32 maxRange,
      |                                                                                           ^~~~~~~~
/home/user/yuzu-mainline/src/video_core/textures/astc.cpp:347:39: error: expected primary-expression before ‘nValues’
  347 |                                   u32 nValues) {
      |                                       ^~~~~~~
/home/user/yuzu-mainline/src/video_core/textures/astc.cpp: In function ‘void ASTCC::DecodeColorValues(u32*, u8*, const u32*, u32, u32)’:
/home/user/yuzu-mainline/src/video_core/textures/astc.cpp:898:5: error: ‘IntegerEncodedVector’ was not declared in this scope; did you mean ‘IntegerEncodedValue’?
  898 |     IntegerEncodedVector decodedColorValues;
      |     ^~~~~~~~~~~~~~~~~~~~
      |     IntegerEncodedValue
/home/user/yuzu-mainline/src/video_core/textures/astc.cpp:901:27: error: ‘decodedColorValues’ was not declared in this scope; did you mean ‘DecodeColorValues’?
  901 |     DecodeIntegerSequence(decodedColorValues, colorStream, range, nValues);
      |                           ^~~~~~~~~~~~~~~~~~
      |                           DecodeColorValues
/home/user/yuzu-mainline/src/video_core/textures/astc.cpp:901:5: error: ‘DecodeIntegerSequence’ was not declared in this scope
  901 |     DecodeIntegerSequence(decodedColorValues, colorStream, range, nValues);
      |     ^~~~~~~~~~~~~~~~~~~~~
/home/user/yuzu-mainline/src/video_core/textures/astc.cpp: At global scope:
/home/user/yuzu-mainline/src/video_core/textures/astc.cpp:1128:59: error: ‘IntegerEncodedVector’ does not name a type; did you mean ‘IntegerEncodedValue’?
 1128 | static void UnquantizeTexelWeights(u32 out[2][144], const IntegerEncodedVector& weights,
      |                                                           ^~~~~~~~~~~~~~~~~~~~
      |                                                           IntegerEncodedValue
/home/user/yuzu-mainline/src/video_core/textures/astc.cpp: In function ‘void ASTCC::UnquantizeTexelWeights(u32 (*)[144], const int&, const ASTCC::TexelWeightParams&, u32, u32)’:
/home/user/yuzu-mainline/src/video_core/textures/astc.cpp:1134:29: error: request for member ‘begin’ in ‘weights’, which is of non-class type ‘const int’
 1134 |     for (auto itr = weights.begin(); itr != weights.end(); ++itr) {
      |                             ^~~~~
/home/user/yuzu-mainline/src/video_core/textures/astc.cpp:1134:53: error: request for member ‘end’ in ‘weights’, which is of non-class type ‘const int’
 1134 |     for (auto itr = weights.begin(); itr != weights.end(); ++itr) {
      |                                                     ^~~
/home/user/yuzu-mainline/src/video_core/textures/astc.cpp:1140:32: error: request for member ‘end’ in ‘weights’, which is of non-class type ‘const int’
 1140 |             if (itr == weights.end()) {
      |                                ^~~
/home/user/yuzu-mainline/src/video_core/textures/astc.cpp: In function ‘void ASTCC::DecompressBlock(const u8*, u32, u32, u32*)’:
/home/user/yuzu-mainline/src/video_core/textures/astc.cpp:1626:5: error: ‘IntegerEncodedVector’ was not declared in this scope; did you mean ‘IntegerEncodedValue’?
 1626 |     IntegerEncodedVector texelWeightValues;
      |     ^~~~~~~~~~~~~~~~~~~~
      |     IntegerEncodedValue
/home/user/yuzu-mainline/src/video_core/textures/astc.cpp:1630:27: error: ‘texelWeightValues’ was not declared in this scope; did you mean ‘texelWeightData’?
 1630 |     DecodeIntegerSequence(texelWeightValues, weightStream, weightParams.m_MaxWeight,
      |                           ^~~~~~~~~~~~~~~~~
      |                           texelWeightData
/home/user/yuzu-mainline/src/video_core/textures/astc.cpp:1630:5: error: ‘DecodeIntegerSequence’ was not declared in this scope
 1630 |     DecodeIntegerSequence(texelWeightValues, weightStream, weightParams.m_MaxWeight,
      |     ^~~~~~~~~~~~~~~~~~~~~
/home/user/yuzu-mainline/src/video_core/textures/astc.cpp: At global scope:
/home/user/yuzu-mainline/src/video_core/textures/astc.cpp:1128:13: warning: ‘void ASTCC::UnquantizeTexelWeights(u32 (*)[144], const int&, const ASTCC::TexelWeightParams&, u32, u32)’ defined but not used [-Wunused-function]
 1128 | static void UnquantizeTexelWeights(u32 out[2][144], const IntegerEncodedVector& weights,
      |             ^~~~~~~~~~~~~~~~~~~~~~
/home/user/yuzu-mainline/src/video_core/textures/astc.cpp:1039:12: warning: ‘u32 ASTCC::UnquantizeTexelWeight(const IntegerEncodedValue&)’ defined but not used [-Wunused-function]
 1039 | static u32 UnquantizeTexelWeight(const IntegerEncodedValue& val) {
      |            ^~~~~~~~~~~~~~~~~~~~~
/home/user/yuzu-mainline/src/video_core/textures/astc.cpp:258:13: warning: ‘void DecodeQus32Block(InputBitStream&, int&, u32)’ defined but not used [-Wunused-function]
  258 | static void DecodeQus32Block(InputBitStream& bits, IntegerEncodedVector& result,
      |             ^~~~~~~~~~~~~~~~
/home/user/yuzu-mainline/src/video_core/textures/astc.cpp:200:13: warning: ‘void DecodeTritBlock(InputBitStream&, int&, u32)’ defined but not used [-Wunused-function]
  200 | static void DecodeTritBlock(InputBitStream& bits, IntegerEncodedVector& result, u32 nBitsPerValue) {
      |             ^~~~~~~~~~~~~~~
make[2]: *** [src/video_core/CMakeFiles/video_core.dir/build.make:1116: src/video_core/CMakeFiles/video_core.dir/textures/astc.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2179: src/video_core/CMakeFiles/video_core.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
`

**Comment by ZantsuRocks** [comment]
At least in the last 3 or 4 tags...

```sh
In file included from /home/wagner/Downloads/yuzu-mainline/src/video_core/renderer_vulkan/fixed_pipeline_state.cpp:12:
/home/wagner/Downloads/yuzu-mainline/src/./video_core/renderer_vulkan/fixed_pipeline_state.h: In member function ‘void Vulkan::FixedPipelineState::VertexInput::SetBinding(std::size_t, bool, u32, u32)’:
/home/wagner/Downloads/yuzu-mainline/src/./video_core/renderer_vulkan/fixed_pipeline_state.h:132:35: error: conversion from ‘u32’ {aka ‘unsigned int’} to ‘short unsigned int’ may change value [-Werror=conversion]
  132 |             binding.stride.Assign(stride);
      |                                   ^~~~~~
In file included from /home/wagner/Downloads/yuzu-mainline/src/./video_core/renderer_vulkan/fixed_pipeline_state.h:10,
                 from /home/wagner/Downloads/yuzu-mainline/src/video_core/renderer_vulkan/fixed_pipeline_state.cpp:12:
/home/wagner/Downloads/yuzu-mainline/src/./common/bit_field.h: In instantiation of ‘constexpr void BitField<Position, Bits, T, EndianTag>::Assign(const T&) [with long unsigned int Position = 0; long unsigned int Bits = 1; T = short unsigned int; EndianTag = KeepTag]’:
/home/wagner/Downloads/yuzu-mainline/src/./video_core/renderer_vulkan/fixed_pipeline_state.h:131:51:   required from here
/home/wagner/Downloads/yuzu-mainline/src/./common/bit_field.h:183:63: error: conversion from ‘int’ to ‘BitField<0, 1, short unsigned int>::StorageTypeWithEndian’ {aka ‘short unsigned int’} may change value [-Werror=conversion]
  183 |         storage = (static_cast<StorageType>(storage) & ~mask) | FormatValue(value);
      |                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
/home/wagner/Downloads/yuzu-mainline/src/./common/bit_field.h: In instantiation of ‘constexpr void BitField<Position, Bits, T, EndianTag>::Assign(const T&) [with long unsigned int Position = 1; long unsigned int Bits = 12; T = short unsigned int; EndianTag = KeepTag]’:
/home/wagner/Downloads/yuzu-mainline/src/./video_core/renderer_vulkan/fixed_pipeline_state.h:132:41:   required from here
/home/wagner/Downloads/yuzu-mainline/src/./common/bit_field.h:183:63: error: conversion from ‘int’ to ‘BitField<1, 12, short unsigned int>::StorageTypeWithEndian’ {aka ‘short unsigned int’} may change value [-Werror=conversion]
```

**Comment by terencode** [comment]
Try again, it should be fixed.

**Comment by ZantsuRocks** [comment]
For me it's fixed.

**Comment by Shoegzer** [comment]
Still not compiling here (latest commit to yuzu-mainline), same errors as above.

**Comment by kevin-olbrich** [comment]
> Still not compiling here (latest commit to yuzu-mainline), same errors as above.

Same here, now, on Fedora 31 with latest packages.

**Comment by jtojnar** [comment]
People are mixing three different issues here:

1. Missing `LZ4_MAX_INPUT_SIZE` is weird. It was introduced in https://github.com/lz4/lz4/commit/a78db582d321446b5167de67eec8ba3239b14bbe, which should be even on old distros like  [OP](https://github.com/yuzu-emu/yuzu/issues/3790#issue-606488593)’s. Maybe try building in a freshly cloned repository and if that fails, bisect.
2. @joker5bb likely has too old Boost installed – `static_vector_options` was added in 1.71.
3. @ZantsuRocks [experienced](https://github.com/yuzu-emu/yuzu/issues/3790#issuecomment-619294311) #3754, which was fixed by https://github.com/yuzu-emu/yuzu/pull/3786.

**Comment by kevin-olbrich** [comment]
> 2\. @joker5bb likely has too old Boost installed – `static_vector_options` was added in 1.71.

True for me. F31 and F32 beta ship boost-1.69.0-15. F32 is a not yet published OS which still lacks that library. :-(

**Comment by joker5bb** [comment]
I am no longer having this issue

**Comment by Shoegzer** [comment]
@jtojnar Thanks, I've been building in fresh repos when it initially failed.  I just bisected, details are in the original post.

@degasus Any ideas on root cause?  From your commit I'm guessing it's based on reliance on an outdated liblz4 shared lib vs. the more recent lib packaged with yuzu externals?

**Comment by jtojnar** [comment]
Looking at the [dev package](https://packages.ubuntu.com/bionic/liblz4-dev), Ubuntu 18.04 uses revision 131 of the library:

```
#   LZ4 - Fast LZ compression algorithm
#   Copyright (C) 2011-2014, Yann Collet.
#   BSD 2-Clause License (http://www.opensource.org/licenses/bsd-license.php)

prefix=/usr
libdir=/usr/lib
includedir=/usr/include

Name: lz4
Description: fast lossless compression algorithm library
URL: http://code.google.com/p/lz4/
Version: 131
Libs: -L/usr/lib -llz4
Cflags: -I/usr/include
```

That already contains `LZ4_MAX_INPUT_SIZE` so I do not understand why the error occurs.

------

But it is still problematic since the revision number is greater than the requested version:

```ShellSession
$ PKG_CONFIG_PATH=/home/jtojnar/Downloads/ubuntu-libzl4-dev/usr/lib/x86_64-linux-gnu/pkgconfig pkg-config "liblz4 >= 1.8.0" --modversion'
131
```

Even though it is much much older.

**Comment by Shoegzer** [comment]
@jtojnar Thanks, that is the installed verison here too (specifically 0.0~r131-2ubuntu3).  I've also updated the original post with a full log at the bottom, in case it provides other clues.

**Comment by degasus** [comment]
Do we need to manually include lz4.h as well instead of just lz4hc.h?

**Comment by degasus** [comment]
The real issue is shown here:
-- Checking for module 'liblz4>=1.8.0'
--   Found liblz4, version 131

They have changed some macros in 1.8.0, and we miss to include lz4.h.
However the version check is wrong, but I have no clue how to implement version checking if they have changed their numbering schema.

**Comment by jtojnar** [comment]
Maybe add an extra check if the returned version contains a period and consider it not found when it does not. Looking at the [tags](https://github.com/lz4/lz4/tags), that should work.

**Comment by bukyapavankumar** [comment]
I compiled linux build today successfully today .is this issue fixed?

**Comment by Shoegzer** [comment]
It is not.

**Comment by bukyapavankumar** [comment]
Then why it is comfiling for me

**Comment by jtojnar** [comment]
Out of the three errors in this issue https://github.com/yuzu-emu/yuzu/issues/3790#issuecomment-620100017, two are caused by old dependencies. To close this issue, the checks in the `externals/CMakeLists.txt` needs to be improved.

The last issue, which I suspect you encountered in the past, has been fixed.

**Comment by racerxdl** [comment]
I had these issues too, but since liblz4 does not have so much deps, I just downloaded the deb files from Ubuntu Disco (20) and installed on my Ubuntu 18.

If anyone wants, I downloaded from auto build https://launchpad.net/ubuntu/+source/lz4/1.8.3-1ubuntu1/+build/16243412

**Comment by chgpalmer** [comment]
For Fedora users with ancient libboost, I had success building Boost from source and building with:
```
cmake -DBoost_NO_SYSTEM_PATHS=TRUE \
      -DBOOST_ROOT=/path/to/boost-dir
```

**Comment by degasus** [comment]
AFAIK this is fixed with the latest master update - both the lz4 and the libboost version check.

**Comment by gabrielbra** [comment]
[  1%] Built target Zycore
[  2%] Built target Zydis
[  2%] Building CXX object externals/dynarmic/src/dynarmic/CMakeFiles/dynarmic.dir/backend/x64/abi.cpp.o
In file included from /home/itmania/yuzu/externals/dynarmic/src/dynarmic/../dynarmic/backend/x64/block_of_code.h:18,
                 from /home/itmania/yuzu/externals/dynarmic/src/dynarmic/backend/x64/abi.cpp:13:
/home/itmania/yuzu/externals/dynarmic/src/dynarmic/../dynarmic/backend/x64/constant_pool.h:8:10: fatal error: bit: No existe el fichero o el directorio
 #include <bit>
          ^~~~~
compilation terminated.
make[2]: *** [externals/dynarmic/src/dynarmic/CMakeFiles/dynarmic.dir/build.make:2110: externals/dynarmic/src/dynarmic/CMakeFiles/dynarmic.dir/backend/x64/abi.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:852: externals/dynarmic/src/dynarmic/CMakeFiles/dynarmic.dir/all] Error 2
make: *** [Makefile:160: all] Error 2

**Comment by gabrielbra** [comment]
constant_pool.h no existe el archivo bit
