### ISSUE TITLE
Yuzu no longer compiles in linux

### ISSUE THREAD

**Issue by Shoegzer** [yuzu-emu/yuzu#7881]
Yuzu no longer compiles in linux if the cmake flag `-DENABLE_WEB_SERVICE=OFF` is added.   The following error is returned, as excerpted from the compilation log below:
```
../src/core/telemetry_session.cpp:170:60:   required from here
/usr/include/c++/11/bits/unique_ptr.h:962:30: error: no matching function for call to ‘Common::Telemetry::NullVisitor::NullVisitor()’
```
Testing information:
* CPU: Intel i7-10870H
* GPU: Nvidia GTX 3070
* OS: Linux Mint 20.3 / kernel 5.13
* Compiler: gcc-11.1.0
* Compilation log: [here](https://pastebin.com/pRNxJ5v8)
* Bad commit per bisect f785f73e9279dcb9cfdee93da694d7a1f55142ea

~~Can provide a bisect if necessary.~~

**Comment by Shoegzer** [comment]
Update: I had time to bisect this to the above commit.  @lioncash can you please assist when you have time?

**Comment by Shoegzer** [comment]
Update #2: The bisect information didn't post originally, but it's there now.  Sorry for any confusion.

**Comment by Shoegzer** [comment]
Looks like you nailed it.  Can you submit a PR?  Regarding your last comment: yuzu only fails to compile if the cmake flag `-DENABLE_WEB_SERVICE=OFF` is added, which I guess should be obvious.  I added this to the post above.
