### ISSUE TITLE
Fails to build with Clang

### ISSUE THREAD

**Issue by jbeich** [yuzu-emu/yuzu#3547]
Regressed by #3505 (unrelated to #3407). CC @namkazt

```c++
src/video_core/shader/decode/xmad.cpp:102:63: error: reference to local binding 'op_b' declared in enclosing function 'VideoCommon::Shader::ShaderIR::DecodeXmad'
                                                              op_b, Immediate(0));
                                                              ^
src/video_core/shader/decode/xmad.cpp:34:46: note: 'op_b' declared here
    auto [is_merge, is_psl, is_high_b, mode, op_b,
                                             ^
src/video_core/shader/decode/xmad.cpp:112:74: error: reference to local binding 'op_b' declared in enclosing function 'VideoCommon::Shader::ShaderIR::DecodeXmad'
                SignedOperation(OperationCode::IBitwiseAnd, is_signed_b, op_b,
                                                                         ^
src/video_core/shader/decode/xmad.cpp:34:46: note: 'op_b' declared here
    auto [is_merge, is_psl, is_high_b, mode, op_b,
                                             ^
```

**Comment by jbeich** [comment]
Oops, documenting Clang version was probably a mistake as the error happens with Clang 8 up to 10.

**Comment by jbeich** [comment]
Oops, duplicate of #3544.
