### PR TITLE
video_core: unbreak build with FFmpeg 5.0

### PR DESCRIPTION
**Pull request by jbeich**
Regressed by https://github.com/ffmpeg/ffmpeg/commit/626535f6a169. From [error log](https://github.com/yuzu-emu/yuzu/files/7904669/yuzu-s20220119_1.log):
```c++
src/video_core/command_classes/codecs/codec.cpp: In member function 'void Tegra::Codec::Initialize()':
src/video_core/command_classes/codecs/codec.cpp:177:36: error: invalid conversion from 'const AVCodec*' to 'AVCodec*' [-fpermissive]
  177 |     av_codec = avcodec_find_decoder(codec);
      |                ~~~~~~~~~~~~~~~~~~~~^~~~~~~
      |                                    |
      |                                    const AVCodec*
```
Runtime tested on [FreeBSD](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=261302) via Super Mario Odyssey (sailing destination previews), Bayonetta 2 (some cut scenes), Metroid Dread (intro).

### CODE REVIEW

**Comment by jbeich** [comment]
Hmm, Linux failed due to:
> ##[error]The server is busy.  Please try again later.

**Comment by lioncash** [comment]
Failure is just an upload timeout, so no worries there.

LGTM, thanks for the patch!

**Review by lioncash — APPROVED** [review]
