### ISSUE TITLE
Fails to build with Clang (due to -Werror)

### ISSUE THREAD

**Issue by jbeich** [yuzu-emu/yuzu#4795]
Regressed by #4786
```c++
$ c++ --version
FreeBSD clang version 11.0.0 (git@github.com:llvm/llvm-project.git llvmorg-11.0.0-rc5-0-g60a25202a7d)
Target: x86_64-unknown-freebsd13.0
Thread model: posix
InstalledDir: /usr/bin

$ cmake -B /tmp/yuzu_build -G Ninja && cmake --build /tmp/yuzu_build
[...]
warning: unknown warning option '-Werror=unused-but-set-parameter'; did you mean '-Werror=unused-parameter'? [-Wunknown-warning-option]
warning: unknown warning option '-Werror=unused-but-set-variable'; did you mean '-Werror=unused-const-variable'? [-Wunknown-warning-option]
[...]
src/core/core_timing_util.cpp:24:56: error: implicit conversion changes signedness: 'long long' to 'unsigned long long' [-Werror,-Wsign-conversion]
        return Hardware::BASE_CLOCK_RATE * (ms.count() / 1000);
                                         ~  ~~~~~~~~~~~^~~~~~
src/core/core_timing_util.cpp:26:44: error: implicit conversion changes signedness: 'std::__1::chrono::duration<long long, std::__1::ratio<1, 1000>>::rep' (aka 'long long') to 'unsigned long long' [-Werror,-Wsign-conversion]
    return (Hardware::BASE_CLOCK_RATE * ms.count()) / 1000;
                                      ~ ~~~^~~~~~~
src/core/core_timing_util.cpp:36:56: error: implicit conversion changes signedness: 'long long' to 'unsigned long long' [-Werror,-Wsign-conversion]
        return Hardware::BASE_CLOCK_RATE * (us.count() / 1000000);
                                         ~  ~~~~~~~~~~~^~~~~~~~~
src/core/core_timing_util.cpp:38:44: error: implicit conversion changes signedness: 'std::__1::chrono::duration<long long, std::__1::ratio<1, 1000000>>::rep' (aka 'long long') to 'unsigned long long' [-Werror,-Wsign-conversion]
    return (Hardware::BASE_CLOCK_RATE * us.count()) / 1000000;
                                      ~ ~~~^~~~~~~
src/core/core_timing_util.cpp:42:56: error: implicit conversion changes signedness: 'std::__1::chrono::duration<long long, std::__1::ratio<1, 1000000000>>::rep' (aka 'long long') to 'u64' (aka 'unsigned long') [-Werror,-Wsign-conversion]
    const u128 temporal = Common::Multiply64Into128(ns.count(), Hardware::BASE_CLOCK_RATE);
                          ~~~~~~                    ~~~^~~~~~~
src/core/core_timing_util.cpp:43:74: error: implicit conversion changes signedness: 'unsigned long' to 's64' (aka 'long') [-Werror,-Wsign-conversion]
    return Common::Divide128On32(temporal, static_cast<u32>(1000000000)).first;
    ~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
src/core/core_timing_util.cpp:47:52: error: implicit conversion changes signedness: 'std::__1::chrono::duration<long long, std::__1::ratio<1, 1000>>::rep' (aka 'long long') to 'u64' (aka 'unsigned long') [-Werror,-Wsign-conversion]
    const u128 temp = Common::Multiply64Into128(ns.count(), Hardware::CNTFREQ);
                      ~~~~~~                    ~~~^~~~~~~
src/core/core_timing_util.cpp:52:52: error: implicit conversion changes signedness: 'std::__1::chrono::duration<long long, std::__1::ratio<1, 1000000>>::rep' (aka 'long long') to 'u64' (aka 'unsigned long') [-Werror,-Wsign-conversion]
    const u128 temp = Common::Multiply64Into128(ns.count(), Hardware::CNTFREQ);
                      ~~~~~~                    ~~~^~~~~~~
src/core/core_timing_util.cpp:57:52: error: implicit conversion changes signedness: 'std::__1::chrono::duration<long long, std::__1::ratio<1, 1000000000>>::rep' (aka 'long long') to 'u64' (aka 'unsigned long') [-Werror,-Wsign-conversion]
    const u128 temp = Common::Multiply64Into128(ns.count(), Hardware::CNTFREQ);
                      ~~~~~~                    ~~~^~~~~~~
src/core/core_timing_util.cpp:67:53: error: implicit conversion changes signedness: 's64' (aka 'long') to 'u64' (aka 'unsigned long') [-Werror,-Wsign-conversion]
    const u128 temporal = Common::Multiply64Into128(cycles, 1000);
                          ~~~~~~                    ^~~~~~
src/core/core_timing_util.cpp:73:53: error: implicit conversion changes signedness: 's64' (aka 'long') to 'u64' (aka 'unsigned long') [-Werror,-Wsign-conversion]
    const u128 temporal = Common::Multiply64Into128(cycles, 1000000000);
                          ~~~~~~                    ^~~~~~
src/core/core_timing_util.cpp:79:53: error: implicit conversion changes signedness: 's64' (aka 'long') to 'u64' (aka 'unsigned long') [-Werror,-Wsign-conversion]
    const u128 temporal = Common::Multiply64Into128(cycles, 1000000);
                          ~~~~~~                    ^~~~~~
In file included from src/core/core_timing.cpp:10:
In file included from src/./common/microprofile.h:23:
externals/./microprofile/microprofile.h:860:39: error: implicit conversion changes signedness: 'unsigned long' to 'int64_t' (aka 'long') [-Werror,-Wsign-conversion]
    int64_t nDifference = ((nEnd<<16) - (nStart<<16));
            ~~~~~~~~~~~    ~~~~~~~~~~~^~~~~~~~~~~~~~
externals/./microprofile/microprofile.h:871:39: error: implicit conversion changes signedness: 'unsigned long' to 'int64_t' (aka 'long') [-Werror,-Wsign-conversion]
    return (MP_LOG_TICK_MASK & nTick) | (e & ~MP_LOG_TICK_MASK);
    ~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
externals/./microprofile/microprofile.h:871:46: error: implicit conversion changes signedness: 'long' to 'unsigned long' [-Werror,-Wsign-conversion]
    return (MP_LOG_TICK_MASK & nTick) | (e & ~MP_LOG_TICK_MASK);
                                           ~ ^~~~~~~~~~~~~~~~~
src/core/core_timing.cpp:143:86: error: implicit conversion changes signedness: 'long' to 'const u64' (aka 'const unsigned long') [-Werror,-Wsign-conversion]
        const u64 next_ticks = nsToCycles(std::chrono::nanoseconds(next_event_time)) + 10U;
                  ~~~~~~~~~~   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
src/core/core_timing.cpp:190:38: error: implicit conversion changes signedness: 'std::__1::chrono::duration<long long, std::__1::ratio<1, 1000000000>>::rep' (aka 'long long') to 'u64' (aka 'unsigned long') [-Werror,-Wsign-conversion]
    global_timer = GetGlobalTimeNs().count();
                 ~ ~~~~~~~~~~~~~~~~~~^~~~~~~
src/core/core_timing.cpp:204:42: error: implicit conversion changes signedness: 'std::__1::chrono::duration<long long, std::__1::ratio<1, 1000000000>>::rep' (aka 'long long') to 'u64' (aka 'unsigned long') [-Werror,-Wsign-conversion]
        global_timer = GetGlobalTimeNs().count();
                     ~ ~~~~~~~~~~~~~~~~~~^~~~~~~
src/core/core_timing.cpp:208:56: error: implicit conversion changes signedness: 'unsigned long' to 'const s64' (aka 'const long') [-Werror,-Wsign-conversion]
        const s64 next_time = event_queue.front().time - global_timer;
                  ~~~~~~~~~   ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
src/core/core_timing.cpp:243:23: error: implicit conversion changes signedness: 'const u64' (aka 'const unsigned long') to 's64' (aka 'long') [-Werror,-Wsign-conversion]
    return CyclesToNs(ticks);
           ~~~~~~~~~~ ^~~~~
src/core/core_timing.cpp:250:23: error: implicit conversion changes signedness: 'const u64' (aka 'const unsigned long') to 's64' (aka 'long') [-Werror,-Wsign-conversion]
    return CyclesToUs(ticks);
           ~~~~~~~~~~ ^~~~~
In file included from src/core/arm/unicorn/arm_unicorn.cpp:8:
In file included from src/./common/microprofile.h:23:
externals/./microprofile/microprofile.h:860:39: error: implicit conversion changes signedness: 'unsigned long' to 'int64_t' (aka 'long') [-Werror,-Wsign-conversion]
    int64_t nDifference = ((nEnd<<16) - (nStart<<16));
            ~~~~~~~~~~~    ~~~~~~~~~~~^~~~~~~~~~~~~~
externals/./microprofile/microprofile.h:871:39: error: implicit conversion changes signedness: 'unsigned long' to 'int64_t' (aka 'long') [-Werror,-Wsign-conversion]
    return (MP_LOG_TICK_MASK & nTick) | (e & ~MP_LOG_TICK_MASK);
    ~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
externals/./microprofile/microprofile.h:871:46: error: implicit conversion changes signedness: 'long' to 'unsigned long' [-Werror,-Wsign-conversion]
    return (MP_LOG_TICK_MASK & nTick) | (e & ~MP_LOG_TICK_MASK);
                                           ~ ^~~~~~~~~~~~~~~~~
src/core/arm/unicorn/arm_unicorn.cpp:222:39: error: implicit conversion changes signedness: 'int' to 'std::__1::array::size_type' (aka 'unsigned long') [-Werror,-Wsign-conversion]
        tregs[i] = &ctx.cpu_registers[i];
                    ~~~               ^
src/core/arm/unicorn/arm_unicorn.cpp:233:42: error: implicit conversion changes signedness: 'int' to 'std::__1::array::size_type' (aka 'unsigned long') [-Werror,-Wsign-conversion]
        tregs[i] = &ctx.vector_registers[i];
                    ~~~                  ^
src/core/arm/unicorn/arm_unicorn.cpp:249:46: error: implicit conversion changes signedness: 'int' to 'std::__1::array::size_type' (aka 'unsigned long') [-Werror,-Wsign-conversion]
        tregs[i] = (void*)&ctx.cpu_registers[i];
                           ~~~               ^
src/core/arm/unicorn/arm_unicorn.cpp:260:49: error: implicit conversion changes signedness: 'int' to 'std::__1::array::size_type' (aka 'unsigned long') [-Werror,-Wsign-conversion]
        tregs[i] = (void*)&ctx.vector_registers[i];
                           ~~~                  ^
src/core/arm/dynarmic/arm_dynarmic_32.cpp:114:16: error: implicit conversion changes signedness: 'const long' to 'u64' (aka 'unsigned long') [-Werror,-Wsign-conversion]
        return std::max<s64>(parent.system.CoreTiming().GetDowncount(), 0);
        ~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/core/arm/dynarmic/arm_dynarmic_32.cpp:214:24: error: implicit conversion changes signedness: 'int' to 'std::__1::array::size_type' (aka 'unsigned long') [-Werror,-Wsign-conversion]
    return jit->Regs()[index];
           ~~~         ^~~~~
src/core/arm/dynarmic/arm_dynarmic_32.cpp:218:17: error: implicit conversion changes signedness: 'int' to 'std::__1::array::size_type' (aka 'unsigned long') [-Werror,-Wsign-conversion]
    jit->Regs()[index] = static_cast<u32>(value);
    ~~~         ^~~~~
src/core/crypto/partition_data_manager.cpp:165:44: error: implicit conversion changes signedness: 's8' (aka 'signed char') to 'std::__1::array::size_type' (aka 'unsigned long') [-Werror,-Wsign-conversion]
        if (!is_zero(keyblob_source_hashes[i])) {
                     ~~~~~~~~~~~~~~~~~~~~~ ^
In file included from src/core/cpu_manager.cpp:6:
In file included from src/./common/microprofile.h:23:
externals/./microprofile/microprofile.h:860:39: error: implicit conversion changes signedness: 'unsigned long' to 'int64_t' (aka 'long') [-Werror,-Wsign-conversion]
    int64_t nDifference = ((nEnd<<16) - (nStart<<16));
            ~~~~~~~~~~~    ~~~~~~~~~~~^~~~~~~~~~~~~~
externals/./microprofile/microprofile.h:871:39: error: implicit conversion changes signedness: 'unsigned long' to 'int64_t' (aka 'long') [-Werror,-Wsign-conversion]
    return (MP_LOG_TICK_MASK & nTick) | (e & ~MP_LOG_TICK_MASK);
    ~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
externals/./microprofile/microprofile.h:871:46: error: implicit conversion changes signedness: 'long' to 'unsigned long' [-Werror,-Wsign-conversion]
    return (MP_LOG_TICK_MASK & nTick) | (e & ~MP_LOG_TICK_MASK);
                                           ~ ^~~~~~~~~~~~~~~~~
src/core/crypto/key_manager.cpp:351:27: error: implicit conversion changes signedness: 'std::size_t' (aka 'unsigned long') to 's64' (aka 'long') [-Werror,-Wsign-conversion]
        if (!save_43.Seek(offset, SEEK_SET)) {
                     ~~~~ ^~~~~~
src/core/crypto/key_manager.cpp:361:30: error: implicit conversion changes signedness: 'unsigned long' to 's64' (aka 'long') [-Werror,-Wsign-conversion]
    if (!save_43.Seek(offset + 0x10, SEEK_SET)) {
                 ~~~~ ~~~~~~~^~~~~~
src/core/arm/dynarmic/arm_dynarmic_64.cpp:151:16: error: implicit conversion changes signedness: 'const long' to 'u64' (aka 'unsigned long') [-Werror,-Wsign-conversion]
        return std::max<s64>(parent.system.CoreTiming().GetDowncount(), 0);
        ~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/core/arm/dynarmic/arm_dynarmic_64.cpp:269:29: error: implicit conversion changes signedness: 'int' to 'std::size_t' (aka 'unsigned long') [-Werror,-Wsign-conversion]
    return jit->GetRegister(index);
                ~~~~~~~~~~~ ^~~~~
src/core/arm/dynarmic/arm_dynarmic_64.cpp:273:22: error: implicit conversion changes signedness: 'int' to 'size_t' (aka 'unsigned long') [-Werror,-Wsign-conversion]
    jit->SetRegister(index, value);
         ~~~~~~~~~~~ ^~~~~
src/core/arm/dynarmic/arm_dynarmic_64.cpp:277:27: error: implicit conversion changes signedness: 'int' to 'std::size_t' (aka 'unsigned long') [-Werror,-Wsign-conversion]
    return jit->GetVector(index);
                ~~~~~~~~~ ^~~~~
src/core/arm/dynarmic/arm_dynarmic_64.cpp:281:20: error: implicit conversion changes signedness: 'int' to 'std::size_t' (aka 'unsigned long') [-Werror,-Wsign-conversion]
    jit->SetVector(index, value);
         ~~~~~~~~~ ^~~~~
In file included from src/core/core.cpp:11:
In file included from src/./common/microprofile.h:23:
externals/./microprofile/microprofile.h:860:39: error: implicit conversion changes signedness: 'unsigned long' to 'int64_t' (aka 'long') [-Werror,-Wsign-conversion]
    int64_t nDifference = ((nEnd<<16) - (nStart<<16));
            ~~~~~~~~~~~    ~~~~~~~~~~~^~~~~~~~~~~~~~
externals/./microprofile/microprofile.h:871:39: error: implicit conversion changes signedness: 'unsigned long' to 'int64_t' (aka 'long') [-Werror,-Wsign-conversion]
    return (MP_LOG_TICK_MASK & nTick) | (e & ~MP_LOG_TICK_MASK);
    ~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
externals/./microprofile/microprofile.h:871:46: error: implicit conversion changes signedness: 'long' to 'unsigned long' [-Werror,-Wsign-conversion]
    return (MP_LOG_TICK_MASK & nTick) | (e & ~MP_LOG_TICK_MASK);
                                           ~ ^~~~~~~~~~~~~~~~~
In file included from src/core/core.cpp:52:
In file included from src/./video_core/renderer_base.h:12:
In file included from src/./core/frontend/emu_window.h:11:
In file included from src/./core/frontend/framebuffer_layout.h:8:
src/./common/math_util.h:30:20: error: implicit conversion changes signedness: 'int' to 'unsigned int' [-Werror,-Wsign-conversion]
            return std::abs(static_cast<std::make_signed_t<T>>(right - left));
            ~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/./core/frontend/framebuffer_layout.h:47:42: note: in instantiation of member function 'Common::Rectangle<unsigned int>::GetWidth' requested here
        return static_cast<float>(screen.GetWidth()) / ScreenUndocked::Width;
                                         ^
src/core/file_sys/content_archive.cpp:208:44: error: implicit conversion changes signedness: 'const std::ptrdiff_t' (aka 'const long') to 'std::__1::vector<FileSys::NCASectionHeader, std::__1::allocator<FileSys::NCASectionHeader>>::size_type' (aka 'unsigned long') [-Werror,-Wsign-conversion]
    std::vector<NCASectionHeader> sections(number_sections);
                                  ~~~~~~~~ ^~~~~~~~~~~~~~~
src/core/file_sys/content_archive.cpp:209:56: error: implicit conversion changes signedness: 'const std::ptrdiff_t' (aka 'const long') to 'unsigned long' [-Werror,-Wsign-conversion]
    const auto length_sections = SECTION_HEADER_SIZE * number_sections;
                                                     ~ ^~~~~~~~~~~~~~~
```

**Comment by jbeich** [comment]
Can you reopen? [Still fails](https://github.com/yuzu-emu/yuzu/files/5419574/yuzu-qt5-s20201020.log):
```c++
src/core/hle/service/ldr/ldr.cpp:26:22: error: unused variable 'ERROR_INVALID_MEMORY_STATE' [-Werror,-Wunused-const-variable]
constexpr ResultCode ERROR_INVALID_MEMORY_STATE{ErrorModule::Loader, 51};
                     ^
src/core/hle/service/ldr/ldr.cpp:36:22: error: unused variable 'ERROR_INVALID_NRR_ADDRESS' [-Werror,-Wunused-const-variable]
constexpr ResultCode ERROR_INVALID_NRR_ADDRESS{ErrorModule::Loader, 85};
                     ^
src/core/hle/service/ns/pl_u.cpp:53:38: error: unused variable 'SHARED_FONTS_TTF' [-Werror,-Wunused-const-variable]
constexpr std::array<const char*, 7> SHARED_FONTS_TTF{
                                     ^
src/core/hle/service/ns/pl_u.cpp:65:17: error: unused variable 'SHARED_FONT_MEM_VADDR' [-Werror,-Wunused-const-variable]
constexpr VAddr SHARED_FONT_MEM_VADDR{0x00000009d3016000ULL};
                ^
src/core/network/network.cpp:151:22: error: implicit conversion loses integer precision: 'Network::(anonymous namespace)::ULONG' (aka 'unsigned long') to 'nfds_t' (aka 'unsigned int') [-Werror,-Wshorten-64-to-32]
    return poll(fds, nfds, timeout);
           ~~~~      ^~~~
In file included from src/input_common/touch_from_button.cpp:5:
In file included from src/./core/frontend/framebuffer_layout.h:8:
src/./common/math_util.h:30:20: error: implicit conversion changes signedness: 'int' to 'unsigned int' [-Werror,-Wsign-conversion]
            return std::abs(static_cast<std::make_signed_t<T>>(right - left));
            ~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/./core/frontend/framebuffer_layout.h:47:42: note: in instantiation of member function 'Common::Rectangle<unsigned int>::GetWidth' requested here
        return static_cast<float>(screen.GetWidth()) / ScreenUndocked::Width;
                                         ^
```

**Comment by lioncash** [comment]
Should be fixed now.
