### PR TITLE
kernel: unlayer CPU interrupt handling

### PR DESCRIPTION
**Pull request by liamwhite**
If a core was interrupted while not running in a Dynarmic context (due to either sleeping, or running code in the kernel), then a bogus interrupt would be set on the Dynarmic context and cause it to exit early even when it didn't need to, resulting in a very minor performance loss.

This removes some extra indirection around interrupt handling, and clears the Dynarmic interrupt when a core's interrupt is cleared, avoiding breaking the loop early.

### CODE REVIEW

**Comment by merryhime** [comment]
This LGTM from my perspective.

**Comment by bunnei** [comment]
Untagging due to:

src\core\arm\dynarmic\arm_dynarmic_32.cpp(147,25): Error C2039: 'interrupt_handlers': is not a member of 'Core::ARM_Dynarmic_32'
build • windows-msvc • Build
src\core\arm\dynarmic\arm_dynarmic_64.cpp(186,25): Error C2039: 'interrupt_handlers': is not a member of 'Core::ARM_Dynarmic_64'
build • windows-msvc • Build
Process 'msbuild.exe' exited with code '1'.

**Comment by liamwhite** [comment]
Build conflicts with #8240

**Review by bunnei — APPROVED** [review]
