### ISSUE TITLE
Yuzu compilation fails on Linux

### ISSUE THREAD

**Issue by Shoegzer** [yuzu-emu/yuzu#2985]
Compiling against https://github.com/yuzu-emu/yuzu/commit/ef9b31783d2c6af6ec21e5a8a4a9de4e340295c7, the following exception is thrown:

```
                 from /home/shoegzer/Desktop/yuzu/yuzu/externals/libzip/lib/zip_crypto_gnutls.c:38:
/usr/include/gnutls/crypto.h:35:10: error: unknown type name ‘gnutls_cipher_algorithm_t’; did you mean ‘gnutls_cipher_hd_t’?
   35 |          gnutls_cipher_algorithm_t cipher,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~
      |          gnutls_cipher_hd_t
...
[ 72%] Linking C static library libcrypto.a
[ 72%] Built target crypto
[ 72%] Linking CXX static library libdynarmic.a
[ 72%] Built target dynarmic
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
```
Note that this does not occur when compiling against yuzu-canary, though it'll probably be getting more attention considering the canary build is deprecated.

Test system is Linux Mint 19.2 with kernel 5.0 and gcc 9.1.0

**Comment by chris062689** [comment]
We only officially support Ubuntu 18.04 LTS as a build platform. Please attempt to rebuild on Ubuntu 18.04 LTS and if this still fails, reopen.

**Comment by ReaperOfSouls1909** [comment]
linux mint is ubuntu 18.04 LTS so is pop os LTS and many others and they all share the same packages

**Comment by ReaperOfSouls1909** [comment]
@Shoegzer just did this on mint and had no errors at all best bet is to try

 sudo apt install libsdl2-dev

sudo apt install build-essential

 sudo apt install cmake git

sudo apt install libqt5webenginewidgets5 libsndio-dev qtbase5-dev libqt5opengl5-dev

Termimal: sudo ln -T /usr/lib/x86_64-linux-gnu/libsndio.so.7.0 /usr/lib/x86_64-linux-gnu/libsndio.so.6.1

Once all of the above is installed, Run the command below to pull and build latest Yuzu

 git clone --recursive https://github.com/yuzu-emu/yuzu && cd yuzu && mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release && make -j8 && sudo make install

**Comment by ReaperOfSouls1909** [comment]
![image](https://user-images.githubusercontent.com/18043258/67151297-84fa0380-f2c4-11e9-9488-aea9cef2bb15.png)

**Comment by Shoegzer** [comment]
@ReaperOfSouls1909 thanks very much for the help.  Those libraries are all installed though.  Again, canary build compiles just fine.  Any other suggestions would be appreciated.

**Comment by lioncash** [comment]
Hi, this is a warning intended for the developers of upstream [libzip](https://github.com/nih-at/libzip). You may want to open an issue on their tracker instead for that.

**Comment by fluffapparition** [comment]
@chris062689 why does it have to be ubuntu 18

**Comment by Shoegzer** [comment]
@lioncash got it.  In any event it's just a warning and probably has little to do with what we're running into as part of this issue.

**Comment by Shoegzer** [comment]
@chris062689 Can you please reopen this issue?  As @ReaperOfSouls1909 mentioned, this is an Ubuntu 18.04 based release with the same package base and compilation is failing.  Thanks.

**Comment by fluffapparition** [comment]
Thank you @fearlesstobi

**Comment by Shoegzer** [comment]
Closing this issue as yuzu compiles successfully now.
