### ISSUE TITLE
Yuzu no longer compiles in linux due to qt-browser issue

### ISSUE THREAD

**Issue by Shoegzer** [yuzu-emu/yuzu#8071]
The following exception is thrown at compile-time:

```
In file included from ../src/yuzu/applets/qt_web_browser.cpp:22:
../src/./yuzu/applets/qt_web_browser.h:173:10: error: ‘thread’ in namespace ‘std’ does not name a type
```
Information:
* CPU: Intel i7-10870H
* OS: Linux Mint 20.3 / kernel 5.13
* Compiler: gcc-11.1.0
* Relevant cmake flags: `-DENABLE_WEB_SERVICE=OFF -DYUZU_USE_QT_WEB_ENGINE=ON`
* Bad commit: f8773e4ba0a650fe2d8f8b9fce0dffb95d0b301e
* Last known good commit: a31c19574982d81d299f94d52fed2a28352f8fe8
* Compile log: [here](https://pastebin.com/V5aJnqpx)

This may have been caused by #8067 as it's the only qt-browser PR between the above commits but can provide a bisect if needed.

**Comment by german77** [comment]
There was a cleanup on #8048 feel free to PR the missing include

**Comment by Shoegzer** [comment]
Thanks, done in #8073.
