### PR TITLE
core: Fix clang build

### LINKED ISSUE #4795: Fails to build with Clang (due to -Werror)
Regressed by #4786
```c++
$ c++ --version
FreeBSD clang version 11.0.0 (git@github.com:llvm/llvm-project.git llvmorg-11.0.0-rc5-0-g60a25202a7d)
Target: x86_64-unknown-freebsd13.0
Thread model: posix
InstalledDir: /usr/bin

$ cmake -B /tmp/yuzu_build -G Ninja && cmake --build /tmp/yuzu_build
[...]
warning: unknown warning option '-Werror=unused-but-set-parameter'; did you mean '-Werror=unused-parameter'? [-Wunknown-warning-option]
warning: unknown warning option '-Werror=unused-but-set-variable'; did you mean '-Werror=unused-const-variable'? [-Wunknown-warning-option]
[...]
src/core/core_timing_util.cpp:24:56: error: implicit conversion changes signedness: 'long long' to 'unsigned long long' [-Werror,-Wsign-conversion]
        return Hardware::BASE_CLOCK_RATE * (ms.count() / 1000);
                                         ~  ~~~~~~~~~~~^~~~~~
src/core/core_timing_util.cpp:26:44: error: implicit conversion changes signedness: 'std::__1::chrono::duration<long long, std::__1::ratio<1, 1000>>::rep' (aka 'long long') to 'unsigned long long' [-Werror,-Wsign-conversion]
    return (Hardware::BASE_CLOCK_RATE * ms.count()) / 1000;
                                      ~ ~~~^~~~~~~
src/core/core_timing_util.cpp:36:56: error: implicit conversion changes signedness: 'long long' to 'unsigned long long' [-Werror,-Wsign-conversion]
        return Hardware::BASE_CLOCK_RATE * (us.count() / 1000000);
                                         ~  ~~~~~~~~~~~^~~~~~~~~
src/core/core_timing_util.cpp:38:44: error: implicit conversion changes signedness: 'std::__1::chrono::duration<long long, std::__1::ratio<1, 1000000>>::rep' (aka 'long long') to 'unsigned long long' [-Werror,-Wsign-conversion]
    return (Hardware::BASE_CLOCK_RATE * us.count()) / 1000000;
                                      ~ ~~~^~~~~~~
src/core/core_timing_util.cpp:42:56: error: implicit conversion changes signedness: 'std::__1::chrono::duration<long long, std::__1::ratio<1, 1000000000>>::rep' (aka 'long long') to 'u64' (aka 'unsigned long') [-Werror,-Wsign-conversion]
    const u128 temporal = Common::Multiply64Into128(ns.count(), Hardware::BASE_CLOCK_RATE);
                          ~~~~~~                    ~~~^~~~~~~
src/core/core_timing_util.cpp:43:74: error: implicit conversion changes signedness: 'unsigned long' to 's64' (aka 'long') [-Werror,-Wsign-conversion]
    return Common::Divide128On32(temporal, static_cast<u32>(1000000000)).first;
    ~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
src/core/core_timing_util.cpp:47:52: error: implicit conversion changes signedness: 'std::__1::chrono::duration<long long, std::__1::ratio<1, 1000>>::rep' (aka 'long long') to 'u64' (aka 'unsigned long') [-Werror,-Wsign-conversion]
    const u128 temp = Common::Multiply64Into128(ns.count(), Hardware::CNTFREQ);
                      ~~~~~~                    ~~~^~~~~~~
src/core/core_timing_util.cpp:52:52: error: implicit conversion changes signedness: 'std::__1::chrono::duration<long long, std::__1::ratio<1, 1000000>>::rep' (aka 'long long') to 'u64' (aka 'unsigned long') [-Werror,-Wsign-conversion]
    const u128 temp = Common::Multiply64Into128(ns.count(), Hardware::CNTFREQ);
                      ~~~~~~                    ~~~^~~~~~~
src/core/core_timing_util.cpp:57:52: error: implicit conversion changes signedness: 'std::__1::chrono::duration<long long, std::__1::ratio<1, 1000000000>>::rep' (aka 'long long') to 'u64' (aka 'unsigned long') [-Werror,-Wsign-conversion]
    const u128 temp = Common::Multiply64Into128(ns.count(), Hardware::CNTFREQ);
                      ~~~~~~                    ~~~^~~~~~~
src/core/core_timing_util.cpp:67:53: error: implicit conversion changes signedness: 's64' (aka 'long') to 'u64' (aka 'unsigned long') [-Werror,-Wsign-conversion]
    const u128 temporal = Common::Multiply64Into128(cycles, 1000);
                          ~~~~~~                    ^~~~~~
src/core/core_timing_util.cpp:73:53: error: implicit conversion changes signedness: 's64' (aka 'long') to 'u64' (aka 'unsigned long') [-Werror,-Wsign-conversion]
    const u128 temporal = Common::Multiply64Into128(cycles, 1000000000);
                          ~~~~~~                    ^~~~~~
src/core/core_timing_util.cpp:79:53: error: implicit conversion changes signedness: 's64' (aka 'long') to 'u64' (aka 'unsigned long') [-Werror,-Wsign-conversion]
    const u128 temporal = Common::Multiply64Into128(cycles, 1000000);
                          ~~~~~~                    ^~~~~~
In file included from src/core/core_timing.cpp:10:
In file included from src/./common/microprofile.h:23:
externals/./microprofile/microprofile.h:860:39: error: implicit conversion changes signedness: 'unsigned long' to 'int64_t' (aka 'long') [-Werror,-Wsign-conversion]
    int64_t nDifference = ((nEnd<<16) - (nStart<<16));
            ~~~~~~~~~~~    ~~~~~~~~~~~^~~~~~~~~~~~~~
externals/./microprofile/microprofile.h:871:39: error: implicit conversion changes signedness: 'unsigned long' to 'int64_t' (aka 'long') [-Werror,-Wsign-conversion]
    return (MP_LOG_TICK_MASK & nTick) | (e & ~MP_LOG_TICK_MASK);
    ~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
externals/./microprofile/microprofile.h:871:46: error: implicit conversion changes signedness: 'long' to 'unsigned long' [-Werror,-Wsign-conversion]
    return (MP_LOG_TICK_MASK & nTick) | (e & ~MP_LOG_TICK_MASK);
                                           ~ ^~~~~~~~~~~~~~~~~
src/core/core_timing.cpp:143:86: error: implicit conversion changes signedness: 'long' to 'const u64' (aka 'const unsigned long') [-Werror,-Wsign-conversion]
        const u64 next_ticks = nsToCycles(std::chrono::nanoseconds(next_event_time)) + 10U;
                  ~~~~~~~~~~   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
src/core/core_timing.cpp:190:38: error: implicit conversion changes signedness: 'std::__1::chrono::duration<long long, std::__1::ratio<1, 1000000000>>::rep' (aka 'long long') to 'u64' (aka 'unsigned long') [-Werror,-Wsign-conversion]
    global_timer = GetGlobalTimeNs().count();
                 ~ ~~~~~~~~~~~~~~~~~~^~~~~~~
src/core/core_timing.cpp:204:42: error: implicit conversion changes signedness: 'std::__1::chrono::duration<long long, std::__1::ratio<1, 1000000000>>::rep' (aka 'long long') to 'u64' (aka 'unsigned long') [-Werror,-Wsign-conversion]
        global_timer = GetGlobalTimeNs().count();
                     ~ ~~~~~~~~~~~~~~~~~~^~~~~~~
src/core/core_timing.cpp:208:56: error: implicit conversion changes signedness: 'unsigned long' to 'const s64' (aka 'const long') [-Werror,-Wsign-conversion]
        const s64 next_time = event_queue.front().time - global_timer;
                  ~~~~~~~~~   ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
src/core/core_timing.cpp:243:23: error: implicit conversion changes signedness: 'const u64' (aka 'const unsigned long') to 's64' (aka 'long') [-Werror,-Wsign-conversion]
    return CyclesToNs(ticks);
           ~~~~~~~~~~ ^~~~~
src/core/core_timing.cpp:250:23: error: implicit conversion changes signedness: 'const u64' (aka 'const unsigned long') to 's64' (aka 'long') [-Werror,-Wsign-conversion]
    return CyclesToUs(ticks);
           ~~~~~~~~~~ ^~~~~
In file included from src/core/arm/unicorn/arm_unicorn.cpp:8:
In file included from src/./common/microprofile.h:23:
externals/./microprofile/microprofile.h:860:39: error: implicit conversion changes signedness: 'unsigned long' to 'int64_t' (aka 'long') [-Werror,-Wsign-conversion]
    int64_t nDifference = ((nEnd<<16) - (nStart<<16));
            ~~~~~~~~~~~    ~~~~~~~~~~~^~~~~~~~~~~~~~
externals/./microprofile/microprofile.h:871:39: error: implicit conversion changes signedness: 'unsigned long' to 'int64_t' (aka 'long') [-Werror,-Wsign-conversion]
    return (MP_LOG_TICK_MASK & nTick) | (e & ~MP_LOG_TICK_MASK);
    ~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
externals/./microprofile/microprofile.h:871:46: error: implicit conversion changes signedness: 'long' to 'unsigned long' [-Werror,-Wsign-conversion]
    return (MP_LOG_TICK_MASK & nTick) | (e & ~MP_LOG_TICK_MASK);
                                           ~ ^~~~~~~~~~~~~~~~~
src/core/arm/unicorn/arm_unicorn.cpp:222:39: error: implicit conversion changes signedness: 'int' to 'std::__1::array::size_type' (aka 'unsigned long') [-Werror,-Wsign-conversion]
        tregs[i] = &ctx.cpu_registers[i];
                    ~~~               ^
src/core/arm/unicorn/arm_unicorn.cpp:233:42: error: implicit conversion changes signedness: 'int' to 'std::__1::array::size_type' (aka 'unsigned long') [-Werror,-Wsign-conversion]
        tregs[i] = &ctx.vector_registers[i];
                    ~~~                  ^
src/core/arm/unicorn/arm_unicorn.cpp:249:46: error: implicit conversion changes signedness: 'int' to 'std::__1::array::size_type' (aka 'unsigned long') [-Werror,-Wsign-conversion]
        tregs[i] = (void*)&ctx.cpu_registers[i];
                           ~~~               ^
src/core/arm/unicorn/arm_unicorn.cpp:260:49: error: implicit conversion changes signedness: 'int' to 'std::__1::array::size_type' (aka 'unsigned long') [-Werror,-Wsign-conversion]
        tregs[i] = (void*)&ctx.vector_registers[i];
                           ~~~                  ^
src/core/arm/dynarmic/arm_dynarmic_32.cpp:114:16: error: implicit conversion changes signedness: 'const long' to 'u64' (aka 'unsigned long') [-Werror,-Wsign-conversion]
        return std::max<s64>(parent.system.CoreTiming().GetDowncount(), 0);
        ~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/core/arm/dynarmic/arm_dynarmic_32.cpp:214:24: error: implicit conversion changes signedness: 'int' to 'std::__1::array::size_type' (aka 'unsigned long') [-Werror,-Wsign-conversion]
    return jit->Regs()[index];
           ~~~         ^~~~~
src/core/arm/dynarmic/arm_dynarmic_32.cpp:218:17: error: implicit conversion changes signedness: 'int' to 'std::__1::array::size_type' (aka 'unsigned long') [-Werror,-Wsign-conversion]
    jit->Regs()[index] = static_cast<u32>(value);
    ~~~         ^~~~~
src/core/crypto/partition_data_manager.cpp:165:44: error: implicit conversion changes signedness: 's8' (aka 'signed char') to 'std::__1::array::size_type' (aka 'unsigned long') [-Werror,-Wsign-conversion]
        if (!is_zero(keyblob_source_hashes[i])) {
                     ~~~~~~~~~~~~~~~~~~~~~ ^
In file included from src/core/cpu_manager.cpp:6:
In file included from src/./common/microprofile.h:23:
externals/./microprofile/microprofile.h:860:39: error: implicit conversion changes signedness: 'unsigned long' to 'int64_t' (aka 'long') [-Werror,-Wsign-conversion]
    int64_t nDifference = ((nEnd<<16) - (nStart<<16));
            ~~~~~~~~~~~    ~~~~~~~~~~~^~~~~~~~~~~~~~
externals/./microprofile/microprofile.h:871:39: error: implicit conversion changes signedness: 'unsigned long' to 'int64_t' (aka 'long') [-Werror,-Wsign-conversion]
    return (MP_LOG_TICK_MASK & nTick) | (e & ~MP_LOG_TICK_MASK);
    ~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
externals/./microprofile/microprofile.h:871:46: error: implicit conversion changes signedness: 'long' to 'unsigned long' [-Werror,-Wsign-conversion]
    return (MP_LOG_TICK_MASK & nTick) | (e & ~MP_LOG_TICK_MASK);
                                           ~ ^~~~~~~~~~~~~~~~~
src/core/crypto/key_manager.cpp:351:27: error: implicit conversion changes signedness: 'std::size_t' (aka 'unsigned long') to 's64' (aka 'long') [-Werror,-Wsign-conversion]
        if (!save_43.Seek(offset, SEEK_SET)) {
                     ~~~~ ^~~~~~
src/core/crypto/key_manager.cpp:361:30: error: implicit conversion changes signedness: 'unsigned long' to 's64' (aka 'long') [-Werror,-Wsign-conversion]
    if (!save_43.Seek(offset + 0x10, SEEK_SET)) {
                 ~~~~ ~~~~~~~^~~~~~
src/core/arm/dynarmic/arm_dynarmic_64.cpp:151:16: error: implicit conversion changes signedness: 'const long' to 'u64' (aka 'unsigned long') [-Werror,-Wsign-conversion]
        return std::max<s64>(parent.system.CoreTiming().GetDowncount(), 0);
        ~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/core/arm/dynarmic/arm_dynarmic_64.cpp:269:29: error: implicit conversion changes signedness: 'int' to 'std::size_t' (aka 'unsigned long') [-Werror,-Wsign-conversion]
    return jit->GetRegister(index);
                ~~~~~~~~~~~ ^~~~~
src/core/arm/dynarmic/arm_dynarmic_64.cpp:273:22: error: implicit conversion changes signedness: 'int' to 'size_t' (aka 'unsigned long') [-Werror,-Wsign-conversion]
    jit->SetRegister(index, value);
         ~~~~~~~~~~~ ^~~~~
src/core/arm/dynarmic/arm_dynarmic_64.cpp:277:27: error: implicit conversion changes signedness: 'int' to 'std::size_t' (aka 'unsigned long') [-Werror,-Wsign-conversion]
    return jit->GetVector(index);
                ~~~~~~~~~ ^~~~~
src/core/arm/dynarmic/arm_dynarmic_64.cpp:281:20: error: implicit conversion changes signedness: 'int' to 'std::size_t' (aka 'unsigned long') [-Werror,-Wsign-conversion]
    jit->SetVector(index, value);
         ~~~~~~~~~ ^~~~~
In file included from src/core/core.cpp:11:
In file included from src/./common/microprofile.h:23:
externals/./microprofile/microprofile.h:860:39: error: implicit conversion changes signedness: 'unsigned long' to 'int64_t' (aka 'long') [-Werror,-Wsign-conversion]
    int64_t nDifference = ((nEnd<<16) - (nStart<<16));
            ~~~~~~~~~~~    ~~~~~~~~~~~^~~~~~~~~~~~~~
externals/./microprofile/microprofile.h:871:39: error: implicit conversion changes signedness: 'unsigned long' to 'int64_t' (aka 'long') [-Werror,-Wsign-conversion]
    return (MP_LOG_TICK_MASK & nTick) | (e & ~MP_LOG_TICK_MASK);
    ~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
externals/./microprofile/microprofile.h:871:46: error: implicit conversion changes signedness: 'long' to 'unsigned long' [-Werror,-Wsign-conversion]
    return (MP_LOG_TICK_MASK & nTick) | (e & ~MP_LOG_TICK_MASK);
                                           ~ ^~~~~~~~~~~~~~~~~
In file included from src/core/core.cpp:52:
In file included from src/./video_core/renderer_base.h:12:
In file included from src/./core/frontend/emu_window.h:11:
In file included from src/./core/frontend/framebuffer_layout.h:8:
src/./common/math_util.h:30:20: error: implicit conversion changes signedness: 'int' to 'unsigned int' [-Werror,-Wsign-conversion]
            return std::abs(static_cast<std::make_signed_t<T>>(right - left));
            ~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/./core/frontend/framebuffer_layout.h:47:42: note: in instantiation of member function 'Common::Rectangle<unsigned int>::GetWidth' requested here
        return static_cast<float>(screen.GetWidth()) / ScreenUndocked::Width;
                                         ^
src/core/file_sys/content_archive.cpp:208:44: error: implicit conversion changes signedness: 'const std::ptrdiff_t' (aka 'const long') to 'std::__1::vector<FileSys::NCASectionHeader, std::__1::allocator<FileSys::NCASectionHeader>>::size_type' (aka 'unsigned long') [-Werror,-Wsign-conversion]
    std::vector<NCASectionHeader> sections(number_sections);
                                  ~~~~~~~~ ^~~~~~~~~~~~~~~
src/core/file_sys/content_archive.cpp:209:56: error: implicit conversion changes signedness: 'const std::ptrdiff_t' (aka 'const long') to 'unsigned long' [-Werror,-Wsign-conversion]
    const auto length_sections = SECTION_HEADER_SIZE * number_sections;
                                                     ~ ^~~~~~~~~~~~~~~
```

### PR DESCRIPTION
**Pull request by lioncash**
Recent changes to the build system that made more warnings be flagged as errors caused building via clang to break.

This should fix #4795

### CODE REVIEW

**Comment by jbeich** [comment]
[Still fails](https://github.com/yuzu-emu/yuzu/files/5393976/yuzu-qt5-s20201015.log):
```c++
In file included from src/core/arm/unicorn/arm_unicorn.cpp:8:
In file included from src/./common/microprofile.h:23:
externals/./microprofile/microprofile.h:871:90: error: implicit conversion changes signedness: 'long' to 'unsigned long' [-Werror,-Wsign-conversion]
    return static_cast<int64_t>((MP_LOG_TICK_MASK & static_cast<uint64_t>(nTick)) | (e & ~MP_LOG_TICK_MASK));
                                                                                       ~ ^~~~~~~~~~~~~~~~~
src/core/arm/dynarmic/arm_dynarmic_64.cpp:151:16: error: implicit conversion changes signedness: 'const long' to 'u64' (aka 'unsigned long') [-Werror,-Wsign-conversion]
        return std::max<s64>(parent.system.CoreTiming().GetDowncount(), 0);
        ~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/core/core_timing_util.cpp:24:42: error: implicit conversion changes signedness: 'unsigned long' to 's64' (aka 'long') [-Werror,-Wsign-conversion]
        return Hardware::BASE_CLOCK_RATE * static_cast<u64>(ms.count() / 1000);
        ~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/core/core_timing_util.cpp:36:42: error: implicit conversion changes signedness: 'unsigned long' to 's64' (aka 'long') [-Werror,-Wsign-conversion]
        return Hardware::BASE_CLOCK_RATE * static_cast<u64>(us.count() / 1000000);
        ~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/core/core_timing_util.cpp:42:52: error: implicit conversion changes signedness: 'std::__1::chrono::duration<long long, std::__1::ratio<1, 1000000000>>::rep' (aka 'long long') to 'u64' (aka 'unsigned long') [-Werror,-Wsign-conversion]
    const u128 temp = Common::Multiply64Into128(ns.count(), Hardware::BASE_CLOCK_RATE);
                      ~~~~~~                    ~~~^~~~~~~
```

**Comment by lioncash** [comment]
@jbeich should be addressed now.

**Comment by jbeich** [comment]
[Not yet](https://github.com/yuzu-emu/yuzu/files/5394405/yuzu-qt5-s20201015.log):
```c++
src/core/file_sys/kernel_executable.cpp:46:48: error: implicit conversion changes signedness: 'int' to 'std::size_t' (aka 'unsigned long') [-Werror,-Wsign-conversion]
                    data[index + start_offset] | data[index + start_offset + 1] << 8;
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/core/file_sys/fsmitm_romfsbuild.cpp:106:17: error: implicit conversion changes signedness: 'const char' to 'unsigned int' [-Werror,-Wsign-conversion]
        hash ^= path[start + i];
             ~~ ^~~~~~~~~~~~~~~
src/core/file_sys/ips_layer.cpp:88:78: error: implicit conversion changes signedness: 'int' to 'u32' (aka 'unsigned int') [-Werror,-Wsign-conversion]
            real_offset = (temp[0] << 24) | (temp[1] << 16) | (temp[2] << 8) | temp[3];
                        ~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
src/core/file_sys/ips_layer.cpp:90:60: error: implicit conversion changes signedness: 'int' to 'u32' (aka 'unsigned int') [-Werror,-Wsign-conversion]
            real_offset = (temp[0] << 16) | (temp[1] << 8) | temp[2];
                        ~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
src/core/file_sys/ips_layer.cpp:185:64: error: implicit conversion changes signedness: 'std::__1::vector<unsigned char, std::__1::allocator<unsigned char>>::size_type' (aka 'unsigned long') to 'std::__1::streamsize' (aka 'long') [-Werror,-Wsign-conversion]
    s.write(reinterpret_cast<const char*>(bytes.data()), bytes.size());
      ~~~~~                                              ~~~~~~^~~~~~
```

**Comment by lioncash** [comment]
Addressed these. If there are any more, please give the complete list, not a snippet of a part of the errors to resolve, so it's quicker to resolve all issues.

**Comment by jbeich** [comment]
> please give the complete list

Adding `-k0` (ninja) [caught](https://github.com/yuzu-emu/yuzu/files/5394666/yuzu-qt5-s20201015.log) ~400 errors.

**Comment by lioncash** [comment]
@jbeich can you run clang over the patch whenever you have the time again? This should significantly cut down on some of the warning spam.

**Comment by jbeich** [comment]
~240 errors are [remaining](https://github.com/yuzu-emu/yuzu/files/5395498/yuzu-qt5-s20201016.log)

**Comment by lioncash** [comment]
How about now? I assume there will still be errors, though I'd assume these will mostly be within audio_core.

**Comment by jbeich** [comment]
184 [remain](https://github.com/yuzu-emu/yuzu/files/5395909/yuzu-qt5-s20201016.log)

> mostly be within audio_core

I've added `-ferror-limit=9999` to expose more in audio_core.

**Comment by lioncash** [comment]
@jbeich How about now? If there's any errors left, there can't be too many remaining.

**Comment by jbeich** [comment]
2 errors [remain](https://github.com/yuzu-emu/yuzu/files/5396750/yuzu-qt5-s20201016.log):
```c++
src/core/hle/service/ldr/ldr.cpp:26:22: error: unused variable 'ERROR_INVALID_MEMORY_STATE' [-Werror,-Wunused-const-variable]
constexpr ResultCode ERROR_INVALID_MEMORY_STATE{ErrorModule::Loader, 51};
                     ^
src/core/hle/service/ldr/ldr.cpp:36:22: error: unused variable 'ERROR_INVALID_NRR_ADDRESS' [-Werror,-Wunused-const-variable]
constexpr ResultCode ERROR_INVALID_NRR_ADDRESS{ErrorModule::Loader, 85};
                     ^
```

**Comment by lioncash** [comment]
Fixed

**Comment by jbeich** [comment]
[Builds fine](https://github.com/yuzu-emu/yuzu/files/5396871/yuzu-qt5-s20201016.log) now

**Comment by jbeich** [comment]
Do you plan to silence unsupported `-Werror=...` like in audio_core? There're 282 instances in the build but after deduplicating those are:
```
warning: unknown warning option '-Werror=class-memaccess'; did you mean '-Werror=class-varargs'? [-Wunknown-warning-option]
warning: unknown warning option '-Werror=unused-but-set-parameter'; did you mean '-Werror=unused-parameter'? [-Wunknown-warning-option]
warning: unknown warning option '-Werror=unused-but-set-variable'; did you mean '-Werror=unused-const-variable'? [-Wunknown-warning-option]
```
```diff
diff --git a/src/input_common/CMakeLists.txt b/src/input_common/CMakeLists.txt
index 7b39a38c1..041ebf469 100644
--- a/src/input_common/CMakeLists.txt
+++ b/src/input_common/CMakeLists.txt
@@ -52,8 +52,8 @@ else()
         -Werror=reorder
         -Werror=shadow
         -Werror=sign-compare
-        -Werror=unused-but-set-parameter
-        -Werror=unused-but-set-variable
+        $<$<CXX_COMPILER_ID:GNU>:-Werror=unused-but-set-parameter>
+        $<$<CXX_COMPILER_ID:GNU>:-Werror=unused-but-set-variable>
         -Werror=unused-variable
     )
 endif()
diff --git a/src/video_core/CMakeLists.txt b/src/video_core/CMakeLists.txt
index 3df54816d..7a67f7cf1 100644
--- a/src/video_core/CMakeLists.txt
+++ b/src/video_core/CMakeLists.txt
@@ -278,7 +278,7 @@ else()
         -Wno-error=sign-conversion
         -Werror=switch
         -Werror=unused-variable
-        -Werror=unused-but-set-variable
-        -Werror=class-memaccess
+        $<$<CXX_COMPILER_ID:GNU>:-Werror=unused-but-set-variable>
+        $<$<CXX_COMPILER_ID:GNU>:-Werror=class-memaccess>
     )
 endif()
```

**Comment by lioncash** [comment]
Those will be fixed in a follow-up. This change just aims to get the clang build working again.
