### ISSUE TITLE
Fails to build with Clang (due to -Werror)

### ISSUE THREAD

**Issue by jbeich** [yuzu-emu/yuzu#5046]
Regressed by #4939. From [error log](https://github.com/yuzu-emu/yuzu/files/5619396/yuzu-qt5-s20201130.log):
```c++
src/input_common/mouse/mouse_input.cpp:60:16: error: implicit conversion changes signedness: 'int' to 'std::__1::array::size_type' (aka 'unsigned long') [-Werror,-Wsign-conversion]
    mouse_info[button_].mouse_origin = Common::MakeVec(x, y);
    ~~~~~~~~~~ ^~~~~~~
src/input_common/mouse/mouse_input.cpp:61:16: error: implicit conversion changes signedness: 'int' to 'std::__1::array::size_type' (aka 'unsigned long') [-Werror,-Wsign-conversion]
    mouse_info[button_].last_mouse_position = Common::MakeVec(x, y);
    ~~~~~~~~~~ ^~~~~~~
src/input_common/mouse/mouse_input.cpp:62:16: error: implicit conversion changes signedness: 'int' to 'std::__1::array::size_type' (aka 'unsigned long') [-Werror,-Wsign-conversion]
    mouse_info[button_].data.pressed = true;
    ~~~~~~~~~~ ^~~~~~~
src/input_common/mouse/mouse_input.cpp:91:16: error: implicit conversion changes signedness: 'int' to 'std::__1::array::size_type' (aka 'unsigned long') [-Werror,-Wsign-conversion]
    mouse_info[button_].tilt_speed = 0;
    ~~~~~~~~~~ ^~~~~~~
src/input_common/mouse/mouse_input.cpp:92:16: error: implicit conversion changes signedness: 'int' to 'std::__1::array::size_type' (aka 'unsigned long') [-Werror,-Wsign-conversion]
    mouse_info[button_].data.pressed = false;
    ~~~~~~~~~~ ^~~~~~~
src/input_common/mouse/mouse_input.cpp:93:16: error: implicit conversion changes signedness: 'int' to 'std::__1::array::size_type' (aka 'unsigned long') [-Werror,-Wsign-conversion]
    mouse_info[button_].data.axis = {0, 0};
    ~~~~~~~~~~ ^~~~~~~
6 errors generated.
```
