### ISSUE TITLE
compile files, error: ‘class boost::system::error_code’ has no member named ‘failed’

### ISSUE THREAD

**Issue by nixtux** [yuzu-emu/yuzu#3487]
Build fails to compile on ubuntu 19.10

> /home/nixtux/src/yuzu_master/src/input_common/udp/client.cpp: In constructor ‘InputCommon::CemuhookUDP::Socket::Socket(const string&, u16, u8, u32, InputCommon::CemuhookUDP::SocketCallback)’:
> /home/nixtux/src/yuzu_master/src/input_common/udp/client.cpp:38:16: error: ‘class boost::system::error_code’ has no member named ‘failed’
>    38 |         if (ec.failed()) {
>       |                ^~~~~~
> make[2]: *** [src/input_common/CMakeFiles/input_common.dir/build.make:128: src/input_common/CMakeFiles/input_common.dir/udp/client.cpp.o] Error 1
> make[1]: *** [CMakeFiles/Makefile2:2544: src/input_common/CMakeFiles/input_common.dir/all] Error 2
> make[1]: *** Waiting for unfinished jobs....
> [ 95%] Built target tests
> make: *** [Makefile:141: all] Error 2
> 

compiles fine before commit 002d9508a04f9cc7de870a3144c798a84fadca77

**Comment by FearlessTobi** [comment]
Did you update all your submodules?

**Comment by nixtux** [comment]
yeah all submodules up to date.

**Comment by kenan1099** [comment]
Same problem here on Debian unstable

**Comment by kenan1099** [comment]
hey i don't know jack shit about this code but does the class errorcode have the function "failed" ?
It might be a typo

**Comment by kenan1099** [comment]
I edited it to "fail" per https://theboostcpplibraries.com/boost.system and im currently rebuilding but my system is running at a snail's pace

**Comment by FearlessTobi** [comment]
https://www.boost.org/doc/libs/1_69_0/libs/system/doc/html/system.html 
It seems like the `failed` function has only been added in Boost 1.69.
Please check what version is used on your system for compilation if possible.

(Apparently for Debian it is only version 1.67)

**Comment by FearlessTobi** [comment]
Please try to compile with https://github.com/yuzu-emu/yuzu/pull/3525.
