### ISSUE TITLE
dyld: Symbol not found: __ZdlPvSt11align_val_t

### ISSUE THREAD

**Issue by NoahRoseLedesma** [yuzu-emu/yuzu#1534]
Trying to run the nightly build on OSX 10.12 gives the following error

```
dyld: Symbol not found: __ZdlPvSt11align_val_t
  Referenced from: /Users/noah/Documents/LOVE/yuzu/./yuzu-cmd (which was built for Mac OS X 10.13)
  Expected in: /usr/lib/libc++.1.dylib
```

**Comment by Hexagon12** [comment]
MacOS is not supported anymore.

Requesting to close.

**Comment by lioncash** [comment]
The actual reason for this, is you need to be on macOS 10.13 or higher.
