### PR TITLE
common: unbreak build on BSDs

### PR DESCRIPTION
**Pull request by jbeich**
Regressed by #3954. From [error log](https://github.com/yuzu-emu/yuzu/files/4848484/yuzu-s20200629.log):
```c++
src/common/memory_detect.cpp:15:10: fatal error: 'sys/sysinfo.h' file not found
#include <sys/sysinfo.h>
         ^~~~~~~~~~~~~~~
```

[sysinfo(2)](http://man7.org/linux/man-pages/man2/sysinfo.2.html) doesn't exist on any of BSDs. [libsysinfo](https://github.com/bsdimp/libsysinfo) relies on [kvm_getswapinfo(3)](https://man.freebsd.org/kvm_getswapinfo/3) which doesn't exist on NetBSD and OpenBSD. Also, installing libsysinfo [is dangerous](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=242236).

### CODE REVIEW

File: src/common/memory_detect.cpp [hunk 1]
```diff
@@ -42,11 +44,22 @@ static MemoryInfo Detect() {
     sysctlbyname("vm.swapusage", &vmusage, &sizeof_vmusage, NULL, 0);
     mem_info.TotalPhysicalMemory = ramsize;
     mem_info.TotalSwapMemory = vmusage.xsu_total;
-#else
+#elif defined(__FreeBSD__)
+    u_long physmem, swap_total;
+    std::size_t sizeof_u_long = sizeof(u_long);
+    // sysctlbyname(const char *, void *, size_t *, const void *, size_t);
+    sysctlbyname("hw.physmem", &physmem, &sizeof_u_long, NULL, 0);
```
Comment (lioncash) [inline src/common/memory_detect.cpp:51]:
```suggestion
    sysctlbyname("hw.physmem", &physmem, &sizeof_u_long, nullptr, 0);
```

File: src/common/memory_detect.cpp [hunk 2]
```diff
@@ -42,11 +44,22 @@ static MemoryInfo Detect() {
...
+    sysctlbyname("vm.swap_total", &swap_total, &sizeof_u_long, NULL, 0);
```
Comment (lioncash) [inline src/common/memory_detect.cpp:52]:
```suggestion
    sysctlbyname("vm.swap_total", &swap_total, &sizeof_u_long, nullptr, 0);
```

File: src/common/memory_detect.cpp (hunk 1 above)
Comment (jbeich) [reply src/common/memory_detect.cpp]: Changing only FreeBSD wouldn't be consistent, so I've applied to macOS as well.

Comment (jbeich) [reply src/common/memory_detect.cpp]: On FreeBSD the change is purely cosmestic, see https://github.com/freebsd/freebsd/commit/c8ed04c26b6758354853a6bed4629f71d0d01a7d
