### PR TITLE
common/virtual_buffer: drop unused includes

### PR DESCRIPTION
**Pull request by jbeich**
Regressed by #3666. Similar to #4208. From [DragonFly build log](https://sting.dragonflybsd.org/dports/logs/emulators___yuzu-qt5.log):
```
src/common/virtual_buffer.cpp
src/common/virtual_buffer.cpp:16:10: fatal error: sys/sysinfo.h: No such file or directory
 #include <sys/sysinfo.h>
          ^~~~~~~~~~~~~~~
```

### CODE REVIEW

File: src/common/virtual_buffer.cpp [hunk 1]
```diff
@@ -5,16 +5,7 @@
 #ifdef _WIN32
 #include <windows.h>
 #else
-#include <stdio.h>
 #include <sys/mman.h>
-#include <sys/types.h>
-#if defined __APPLE__ || defined __FreeBSD__ || defined __OpenBSD__
```
Comment (ameerj) [inline src/common/virtual_buffer.cpp:11]: You might want to keep 
```c++
#if defined __APPLE__
```
Only remove the directive that impacts you directly.

Comment (jbeich) [reply src/common/virtual_buffer.cpp:11]: Builds fine on FreeBSD, so `#include <sys/sysctl.h>` is confurmed to be unused.

Comment (jbeich) [reply src/common/virtual_buffer.cpp:11]: Also, Yuzu (unlike Dolphin) never supported Haiku.

**Comment by bunnei** [comment]
LGTM, thank you!
