### ISSUE TITLE
Yuzu no longer compiles in linux (gcc 7.3.0, compilation error in boost/icl)

### ISSUE THREAD

**Issue by Shoegzer** [yuzu-emu/yuzu#2255]
On test system (Linux Mint 19.2 x64, 4.18 kernel, gcc 7.3.0), and as of 41566c615b86183c4dbec5a6bc7596ed4d8a116b, neither yuzu nor yuzu-canary compiles anymore.  Last successful compile was on Feb 25th (master-95c37df87) but have not tried since then (willing to bisect if necessary though).  

Messages thrown to terminal during compilation start with:
```
from /home/tester/Desktop/yuzu/yuzu/externals/dynarmic/src/backend/x64/a32_interface.cpp:9:
/usr/include/boost/icl/type_traits/type_to_string.hpp:56:12: error: partial specialization of ‘struct boost::icl::type_to_string<Unary<Type> >’ after instantiation of ‘struct boost::icl::type_to_string<std::__cxx11::basic_string<char> >’ [-fpermissive]
     struct type_to_string<Unary<Type> >
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated due to -Wfatal-errors.
```

**Comment by Yvar192** [comment]
Succesfully replicated this on ElementaryOS (Ubuntu 18.04 based).

**Comment by alinach120602** [comment]
I can not replicate this issue. 
Arch Linux 5.0

**Comment by MerryMage** [comment]
Please ensure the version of boost you're using is at least 1.66 (released Dec 2017). Alternatively compile against the bundled version of boost we provide.

Related issue: citra-emu/citra#3520

**Comment by Shoegzer** [comment]
Ah yes, thanks @MerryMage.   Currently CMakeLists.txt checks for libboost 1.64.0 before falling back to externals, rather than 1.66.0 as recently required.  In cases such as distros which use the Ubuntu repo which use 1.65.0, cmake never falls back - so the find_package and message lines of the boost section of CMakeList.txt should be updated.  This will fix the issue for others without further manual intervention:
```
find_package(Boost 1.66.0 QUIET)
if (NOT Boost_FOUND)
    message(STATUS "Boost 1.66.0 or newer not found, falling back to externals")

    set(BOOST_ROOT "${PROJECT_SOURCE_DIR}/externals/boost")
    set(Boost_NO_SYSTEM_PATHS OFF)
    find_package(Boost QUIET REQUIRED)
endif()
```

**Comment by Yvar192** [comment]
This fixed the issue for me, yuzu now compiles successfully. You should close this issue when #2257 gets merged.
