### PR TITLE
InputCommon: Fix implicit conversion in mouse input

### LINKED ISSUE #5046: Fails to build with Clang (due to -Werror)
Regressed by #4939. From [error log](https://github.com/yuzu-emu/yuzu/files/5619396/yuzu-qt5-s20201130.log):
```c++
src/input_common/mouse/mouse_input.cpp:60:16: error: implicit conversion changes signedness: 'int' to 'std::__1::array::size_type' (aka 'unsigned long') [-Werror,-Wsign-conversion]
    mouse_info[button_].mouse_origin = Common::MakeVec(x, y);
    ~~~~~~~~~~ ^~~~~~~
src/input_common/mouse/mouse_input.cpp:61:16: error: implicit conversion changes signedness: 'int' to 'std::__1::array::size_type' (aka 'unsigned long') [-Werror,-Wsign-conversion]
    mouse_info[button_].last_mouse_position = Common::MakeVec(x, y);
    ~~~~~~~~~~ ^~~~~~~
src/input_common/mouse/mouse_input.cpp:62:16: error: implicit conversion changes signedness: 'int' to 'std::__1::array::size_type' (aka 'unsigned long') [-Werror,-Wsign-conversion]
    mouse_info[button_].data.pressed = true;
    ~~~~~~~~~~ ^~~~~~~
src/input_common/mouse/mouse_input.cpp:91:16: error: implicit conversion changes signedness: 'int' to 'std::__1::array::size_type' (aka 'unsigned long') [-Werror,-Wsign-conversion]
    mouse_info[button_].tilt_speed = 0;
    ~~~~~~~~~~ ^~~~~~~
src/input_common/mouse/mouse_input.cpp:92:16: error: implicit conversion changes signedness: 'int' to 'std::__1::array::size_type' (aka 'unsigned long') [-Werror,-Wsign-conversion]
    mouse_info[button_].data.pressed = false;
    ~~~~~~~~~~ ^~~~~~~
src/input_common/mouse/mouse_input.cpp:93:16: error: implicit conversion changes signedness: 'int' to 'std::__1::array::size_type' (aka 'unsigned long') [-Werror,-Wsign-conversion]
    mouse_info[button_].data.axis = {0, 0};
    ~~~~~~~~~~ ^~~~~~~
6 errors generated.
```

### PR DESCRIPTION
**Pull request by german77**
Fixes #5046

### CODE REVIEW

File: src/input_common/mouse/mouse_input.cpp [hunk 1]
```diff
@@ -54,12 +54,13 @@ void Mouse::PressButton(int x, int y, int button_) {
     }
 
     int button = 1 << button_;
+    std::size_t button_index = static_cast<std::size_t>(button_);
```
Comment (lioncash) [inline src/input_common/mouse/mouse_input.cpp:57]:
```suggestion
    const auto button_index = static_cast<std::size_t>(button_);
```

File: src/input_common/mouse/mouse_input.cpp [hunk 2]
```diff
@@ -86,11 +87,12 @@ void Mouse::ReleaseButton(int button_) {
...
```
Comment (lioncash) [inline src/input_common/mouse/mouse_input.cpp:90]:
```suggestion
    const auto button_index = static_cast<std::size_t>(button_);
```

**Review by lioncash — APPROVED** [review]
