### ISSUE TITLE
Build error in canary with Linux GCC

### ISSUE THREAD

**Issue by gdelazzari** [yuzu-emu/yuzu#1995]
The master branch from the yuzu-canary repo fails to build on Linux with GCC 8.2.1

```
yuzu-canary/src/yuzu/configuration/config.cpp: In member function ‘void Config::SaveValues()’:
yuzu-canary/src/yuzu/configuration/config.cpp:666:93: error: conversion from ‘std::chrono::duration<long int>::rep’ {aka ‘long int’} to ‘const QVariant’ is ambiguous
                         Settings::values.custom_rtc.value_or(std::chrono::seconds{}).count());
                                                                                             ^
In file included from /usr/include/qt/QtCore/qsettings.h:44,
                 from /usr/include/qt/QtCore/QSettings:1,
                 from yuzu-canary/src/yuzu/configuration/config.cpp:5:
/usr/include/qt/QtCore/qvariant.h:222:5: note: candidate: ‘QVariant::QVariant(float)’
     QVariant(float f);
     ^~~~~~~~
/usr/include/qt/QtCore/qvariant.h:221:5: note: candidate: ‘QVariant::QVariant(double)’
     QVariant(double d);
     ^~~~~~~~
/usr/include/qt/QtCore/qvariant.h:220:5: note: candidate: ‘QVariant::QVariant(bool)’
     QVariant(bool b);
     ^~~~~~~~
/usr/include/qt/QtCore/qvariant.h:219:5: note: candidate: ‘QVariant::QVariant(qulonglong)’
     QVariant(qulonglong ull);
     ^~~~~~~~
/usr/include/qt/QtCore/qvariant.h:218:5: note: candidate: ‘QVariant::QVariant(qlonglong)’
     QVariant(qlonglong ll);
     ^~~~~~~~
/usr/include/qt/QtCore/qvariant.h:217:5: note: candidate: ‘QVariant::QVariant(uint)’
     QVariant(uint ui);
     ^~~~~~~~
/usr/include/qt/QtCore/qvariant.h:216:5: note: candidate: ‘QVariant::QVariant(int)’
     QVariant(int i);
     ^~~~~~~~
In file included from /usr/include/qt/QtCore/QSettings:1,
                 from yuzu-canary/src/yuzu/configuration/config.cpp:5:
/usr/include/qt/QtCore/qsettings.h:166:10: note:   initializing argument 2 of ‘void QSettings::setValue(const QString&, const QVariant&)’
     void setValue(const QString &key, const QVariant &value);
          ^~~~~~~~
```

May this also be the reason there are no more Linux builds automatically compiled by the CI?

(changing the line
```cpp
qt_config->setValue("custom_rtc", Settings::values.custom_rtc.value_or(std::chrono::seconds{}).count());
```
to
```cpp
qt_config->setValue("custom_rtc", static_cast<qlonglong>(Settings::values.custom_rtc.value_or(std::chrono::seconds{}).count()));
```
fixes the issue, but it's pretty ugly so I'm not submitting a PR but reporting here)

**Comment by gdelazzari** [comment]
Sorry, I just noticed this was already reported, I'm closing and posting this issue to PR #1959 as a reminder to fix
